# generated by datamodel-codegen:
#   filename:  siep_schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class SIEPBeliefBlock(BaseModel):
    prior: float = Field(0.5, title="Prior")
    posterior: float = Field(0.5, title="Posterior")
    revision_cause: str | None = Field(None, title="Revision Cause")


class SIEPGroundingBlock(BaseModel):
    contingency_verified: bool | None = Field(None, title="Contingency Verified")
    contingency_score: float | None = Field(None, title="Contingency Score")
    repair_reason: str | None = Field(None, title="Repair Reason")
    challenges: list[str] = Field([], title="Challenges")


class SIEPUtteranceBlock(BaseModel):
    evidence: list[str] = Field([], title="Evidence")
    addresses_evidence: list[str] = Field([], title="Addresses Evidence")
    turn_depth: int = Field(0, title="Turn Depth")


class SIEPMessagePayload(BaseModel):
    utterance: SIEPUtteranceBlock = Field(
        {"evidence": [], "addresses_evidence": [], "turn_depth": 0},
        validate_default=True,
    )
    grounding: SIEPGroundingBlock = Field(
        {
            "contingency_verified": None,
            "contingency_score": None,
            "repair_reason": None,
            "challenges": [],
        },
        validate_default=True,
    )
    belief: SIEPBeliefBlock = Field(
        {"prior": 0.5, "posterior": 0.5, "revision_cause": None}, validate_default=True
    )
