// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package l9

import "encoding/json"
import "errors"
import "fmt"

// A participant in a protocol exchange — can be a human, an AI agent, or a system.
// Multiple actors are listed in L9Header.actors to identify sender(s) and
// receiver(s).
type Actor struct {
	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Role corresponds to the JSON schema field "role".
	Role string `json:"role" yaml:"role" mapstructure:"role"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Actor) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Actor: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Actor: required")
	}
	if _, ok := raw["role"]; raw != nil && !ok {
		return fmt.Errorf("field role in Actor: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Actor: required")
	}
	type Plain Actor
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Actor(plain)
	return nil
}

// Agent epistemic (belief/knowledge) state at the time the message was sent.
// Currently a placeholder — fields will be added as the model is defined.
type Epistemic map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Epistemic) UnmarshalJSON(value []byte) error {
	type Plain Epistemic
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Epistemic(plain)
	return nil
}

// Logical grouping of actors — e.g. a team, session, or conversation thread.
// Used in L9Header to scope the message to a shared context.
type Group struct {
	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Group) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Group: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Group: required")
	}
	type Plain Group
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Group(plain)
	return nil
}

// Routing and metadata envelope for every L9 message.
// The CFN layer reads the header — especially `kind` and `sub_kind` —
// to decide which Cognitive Engine (CE) should handle the message.
type L9Header struct {
	// Actors corresponds to the JSON schema field "actors".
	Actors []Actor `json:"actors" yaml:"actors" mapstructure:"actors"`

	// Epistemic corresponds to the JSON schema field "epistemic".
	Epistemic *L9HeaderEpistemic `json:"epistemic,omitempty,omitzero" yaml:"epistemic,omitempty" mapstructure:"epistemic,omitempty"`

	// Group corresponds to the JSON schema field "group".
	Group Group `json:"group" yaml:"group" mapstructure:"group"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Policy corresponds to the JSON schema field "policy".
	Policy *L9HeaderPolicy `json:"policy,omitempty,omitzero" yaml:"policy,omitempty" mapstructure:"policy,omitempty"`

	// Protocol corresponds to the JSON schema field "protocol".
	Protocol string `json:"protocol" yaml:"protocol" mapstructure:"protocol"`

	// Provenance corresponds to the JSON schema field "provenance".
	Provenance *L9HeaderProvenance `json:"provenance,omitempty,omitzero" yaml:"provenance,omitempty" mapstructure:"provenance,omitempty"`

	// Semantic corresponds to the JSON schema field "semantic".
	Semantic SemanticContext `json:"semantic" yaml:"semantic" mapstructure:"semantic"`

	// SubKind corresponds to the JSON schema field "sub_kind".
	SubKind string `json:"sub_kind" yaml:"sub_kind" mapstructure:"sub_kind"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

// Agent epistemic (belief/knowledge) state at the time the message was sent.
// Currently a placeholder — fields will be added as the model is defined.
type L9HeaderEpistemic map[string]interface{}

// Data governance and access-control labels applied to the message.
// ## TODO Nandu, Peter please review
type L9HeaderPolicy struct {
	// Propagation corresponds to the JSON schema field "propagation".
	Propagation string `json:"propagation" yaml:"propagation" mapstructure:"propagation"`

	// RetentionPolicy corresponds to the JSON schema field "retention_policy".
	RetentionPolicy string `json:"retention_policy" yaml:"retention_policy" mapstructure:"retention_policy"`

	// Sensitivity corresponds to the JSON schema field "sensitivity".
	Sensitivity string `json:"sensitivity" yaml:"sensitivity" mapstructure:"sensitivity"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *L9HeaderPolicy) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var l9HeaderPolicy_0 L9HeaderPolicy_0
	var errs []error
	if err := l9HeaderPolicy_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain L9HeaderPolicy
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = L9HeaderPolicy(plain)
	return nil
}

// Tracks the origin and lineage of a message — who created it, from what source,
// and through which transformations. Fields TBD.
type L9HeaderProvenance map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *L9Header) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["actors"]; raw != nil && !ok {
		return fmt.Errorf("field actors in L9Header: required")
	}
	if _, ok := raw["group"]; raw != nil && !ok {
		return fmt.Errorf("field group in L9Header: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in L9Header: required")
	}
	if _, ok := raw["protocol"]; raw != nil && !ok {
		return fmt.Errorf("field protocol in L9Header: required")
	}
	if _, ok := raw["semantic"]; raw != nil && !ok {
		return fmt.Errorf("field semantic in L9Header: required")
	}
	if _, ok := raw["sub_kind"]; raw != nil && !ok {
		return fmt.Errorf("field sub_kind in L9Header: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in L9Header: required")
	}
	type Plain L9Header
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = L9Header(plain)
	return nil
}

// A complete L9 message: header (routing/metadata) + payload (content).
// This is the top-level structure passed between agents and through the CFN.
type L9Json struct {
	// Header corresponds to the JSON schema field "header".
	Header L9Header `json:"header" yaml:"header" mapstructure:"header"`

	// Payload corresponds to the JSON schema field "payload".
	Payload L9Payload `json:"payload" yaml:"payload" mapstructure:"payload"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *L9Json) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["header"]; raw != nil && !ok {
		return fmt.Errorf("field header in L9Json: required")
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in L9Json: required")
	}
	type Plain L9Json
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = L9Json(plain)
	return nil
}

// The actual content being carried by an L9 message.
// The `type` field describes the payload format; `data` holds the content.
type L9Payload struct {
	// Data corresponds to the JSON schema field "data".
	Data L9PayloadData `json:"data" yaml:"data" mapstructure:"data"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

type L9PayloadData map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *L9Payload) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in L9Payload: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in L9Payload: required")
	}
	type Plain L9Payload
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = L9Payload(plain)
	return nil
}

// Data governance and access-control labels applied to the message.
// ## TODO Nandu, Peter please review
type PolicyLabel struct {
	// Propagation corresponds to the JSON schema field "propagation".
	Propagation string `json:"propagation" yaml:"propagation" mapstructure:"propagation"`

	// RetentionPolicy corresponds to the JSON schema field "retention_policy".
	RetentionPolicy string `json:"retention_policy" yaml:"retention_policy" mapstructure:"retention_policy"`

	// Sensitivity corresponds to the JSON schema field "sensitivity".
	Sensitivity string `json:"sensitivity" yaml:"sensitivity" mapstructure:"sensitivity"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PolicyLabel) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["propagation"]; raw != nil && !ok {
		return fmt.Errorf("field propagation in PolicyLabel: required")
	}
	if _, ok := raw["retention_policy"]; raw != nil && !ok {
		return fmt.Errorf("field retention_policy in PolicyLabel: required")
	}
	if _, ok := raw["sensitivity"]; raw != nil && !ok {
		return fmt.Errorf("field sensitivity in PolicyLabel: required")
	}
	type Plain PolicyLabel
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PolicyLabel(plain)
	return nil
}

// Tracks the origin and lineage of a message — who created it, from what source,
// and through which transformations. Fields TBD.
type Provenance map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Provenance) UnmarshalJSON(value []byte) error {
	type Plain Provenance
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Provenance(plain)
	return nil
}

type L9HeaderEpistemic_0 = Epistemic

// Describes the semantic/ontological framework needed to correctly interpret the
// payload.
// The CFN routing layer uses this to select appropriate cognitive engines (CEs).
type SemanticContext struct {
	// CognitionProtocol corresponds to the JSON schema field "cognition_protocol".
	CognitionProtocol string `json:"cognition_protocol" yaml:"cognition_protocol" mapstructure:"cognition_protocol"`

	// OntologyRef corresponds to the JSON schema field "ontology_ref".
	OntologyRef string `json:"ontology_ref" yaml:"ontology_ref" mapstructure:"ontology_ref"`

	// SchemaID corresponds to the JSON schema field "schema_id".
	SchemaID string `json:"schema_id" yaml:"schema_id" mapstructure:"schema_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SemanticContext) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["cognition_protocol"]; raw != nil && !ok {
		return fmt.Errorf("field cognition_protocol in SemanticContext: required")
	}
	if _, ok := raw["ontology_ref"]; raw != nil && !ok {
		return fmt.Errorf("field ontology_ref in SemanticContext: required")
	}
	if _, ok := raw["schema_id"]; raw != nil && !ok {
		return fmt.Errorf("field schema_id in SemanticContext: required")
	}
	type Plain SemanticContext
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SemanticContext(plain)
	return nil
}

type L9HeaderProvenance_0 = Provenance

type L9HeaderPolicy_0 = PolicyLabel
