# SPDX-FileCopyrightText: Copyright (c) Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0
#
# Required metadata
sonar.projectKey=ioc-cfn-protocols-models
sonar.projectName=SRE platform demo
sonar.projectVersion=1.1

# Encoding of the source files
sonar.sourceEncoding=UTF-8
