# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

"""SIEP grounding verifier.

SIEP operates on three L9 kinds only: intent, exchange, commit.
Contingency handling (repair cycles) is the responsibility of CIP,
a peer subprotocol at the same layer. If a contingency message is
received by SIEPEngine, a SIEPProtocolError is raised.

When grounding fails on an exchange, SIEPEngine raises GroundingFailure
so the caller (or CIP) can decide how to handle it.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Set, Tuple

from ai.outshift.data_model import L9
from SSTP.subprotocol.siep.src.siep_models import siep_parents, siep_epistemic
from SSTP.subprotocol.siep.src.builder import (
    EpistemicState,
    Kind,
    RevisionCause,
    SIEPBelief,
    SIEPGrounding,
    SIEPMessageBuilder,
    SIEPPayload,
    SIEPUtterance,
    contingency_score,
)
from SSTP.subprotocol.siep.src.siep_payload import SIEPMessagePayload
from SSTP.subprotocol.siep.src.tomcore.cognition import TheoryOfMindEngine
from SSTP.subprotocol.siep.src.tomcore.llm import LiteLLMClient, NoOpLLMClient

SIEP_KINDS = {Kind.intent, Kind.exchange, Kind.commit}


class SIEPProtocolError(Exception):
    """Raised when a message kind not supported by SIEP is received."""


class GroundingFailure(Exception):
    """Raised when an exchange fails the grounding contingency check.

    Attributes:
        msg      – the L9 exchange that failed grounding
        score    – computed contingency overlap score
        evidence – the prior evidence the incoming message was checked against
    """
    def __init__(self, msg: L9, score: float, prior_evidence: List[str]) -> None:
        self.msg = msg
        self.score = score
        self.prior_evidence = prior_evidence
        super().__init__(
            f"Grounding failed for message {msg.header.message.id}: "
            f"score={score:.4f} below THETA_C={THETA_C}"
        )


def _make_llm_client():
    import os
    if os.environ.get("LLM_API_KEY") or os.environ.get("LLM_BASE_URL"):
        return LiteLLMClient()
    return NoOpLLMClient()


THETA_C = 0.40


def _concept(msg: L9) -> Optional[str]:
    ep = siep_epistemic(msg)
    return ep.concept_id if ep else None


def _sender_id(msg: L9) -> str:
    actors = msg.header.participants.actors
    if not actors:
        raise ValueError("SIEP L9 message is missing a sender actor.")
    return actors[0].id


def _siep_payload(msg: L9) -> SIEPMessagePayload:
    return SIEPMessagePayload.model_validate(msg.payload.data)


class SIEPEngine:
    """Processes SIEP L9 messages (intent, exchange, commit only).

    Raises:
        SIEPProtocolError – if a ``contingency`` or unsupported kind is received.
        GroundingFailure  – if an exchange fails the contingency grounding check.
    """

    def __init__(self, agent_id: str, episode_urn: str) -> None:
        self.agent_id = agent_id
        self.episode = episode_urn
        self._priors: Dict[Tuple[str, str], SIEPBelief] = {}
        self._last_exchange: Dict[str, L9] = {}
        self._tom = TheoryOfMindEngine(_make_llm_client())
        self._seeded_peers: Set[str] = set()

    def process(self, msg: L9) -> List[L9]:
        """Process an incoming L9 message.

        Only ``intent``, ``exchange``, and ``commit`` kinds are accepted.
        Receiving a ``contingency`` message raises ``SIEPProtocolError`` —
        contingency handling belongs to CIP.
        """
        kind = msg.header.kind
        if kind not in SIEP_KINDS:
            raise SIEPProtocolError(
                f"SIEP does not handle kind '{kind.value}'. "
                "Contingency and repair cycles are managed by CIP."
            )
        if kind == Kind.intent:
            return []
        if kind == Kind.exchange:
            return self._on_exchange(msg)
        # commit — acknowledge, no response generated by the engine
        return []

    def _on_exchange(self, msg: L9) -> List[L9]:
        sender = _sender_id(msg)
        siep_payload = _siep_payload(msg)
        concept = _concept(msg) or ""
        utterance_text = siep_payload.utterance.text if siep_payload.utterance else ""

        # Seed TOM peer model on first contact
        if sender not in self._seeded_peers:
            self._tom.agent(self.agent_id).seed_peer(sender, sender, {"task_goal": concept})
            self._seeded_peers.add(sender)

        # Record prior belief (taskwork phase)
        epistemic = siep_epistemic(msg)
        if epistemic and epistemic.state == EpistemicState.taskwork.value:
            key = (sender, concept)
            if key not in self._priors:
                self._priors[key] = SIEPBelief(
                    prior=siep_payload.belief.prior,
                    posterior=siep_payload.belief.posterior,
                    revision_cause=RevisionCause.semantic_memory,
                )
            self._last_exchange[sender] = msg
            return []

        # Grounding check
        prior = self._last_exchange.get(sender)
        prior_payload = _siep_payload(prior) if prior else None
        prior_evidence = prior_payload.utterance.evidence if prior_payload else []
        score = contingency_score(siep_payload.utterance.evidence, prior_evidence)
        self._last_exchange[sender] = msg

        # Update TOM peer model with observed alignment score
        self._tom.agent(self.agent_id).update_peer(
            sender, utterance_text or "", concept, alignment_score=score
        )
        drift = self._tom.agent(self.agent_id).drift_signals()

        # TOM drift can escalate a borderline pass to a GroundingFailure
        anchor_gap = drift.get("anchor_gap", 0.0)
        ema_alignment = drift.get("ema_alignment", 1.0)
        force_fail = anchor_gap > 0.3 and ema_alignment < THETA_C

        if score >= THETA_C and not force_fail:
            return [self._grounding_ok(msg, score)]

        raise GroundingFailure(msg, score, prior_evidence)

    def _grounding_ok(self, prior: L9, score: float) -> L9:
        concept = _concept(prior)
        my_belief = self._priors.get((self.agent_id, concept or ""))
        evidence = _siep_payload(prior).utterance.evidence
        return (
            self._builder()
            .exchange().grounding().asserted()
            .concept(concept or "")
            .parents(prior.header.message.id)
            .payload(SIEPPayload(
                utterance=SIEPUtterance(evidence=evidence, addresses_evidence=evidence),
                grounding=SIEPGrounding(contingency_verified=True, contingency_score=round(score, 4)),
                belief=SIEPBelief(
                    prior=my_belief.prior if my_belief else 0.5,
                    posterior=my_belief.posterior if my_belief else 0.5,
                    revision_cause=RevisionCause.grounded_argument,
                ),
            ))
            .build()
        )

    def _builder(self) -> SIEPMessageBuilder:
        return SIEPMessageBuilder(self.episode, self.agent_id)


__all__ = ["THETA_C", "SIEP_KINDS", "SIEPProtocolError", "GroundingFailure", "SIEPEngine"]

