# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# generated by datamodel-codegen:
#   filename:  sab_schema.json

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Any

from pydantic import BaseModel, Field, RootModel


class Encoding(Enum):
    json = "json"
    structured_text = "structured_text"
    hybrid = "hybrid"


class NegotiateCommitSemanticContext(BaseModel):
    schema_version: str = Field("1.0", title="Schema Version")
    encoding: Encoding = Field("json", title="Encoding")
    session_id: str = Field(..., title="Session Id")
    outcome: str = Field(
        ...,
        description=(
            "High-level outcome: 'agreement' — consensus reached; 'disagreement' — step"
            " budget exhausted; 'broken' — a participant dropped out or returned an"
            " invalid offer; 'error' — pipeline exception."
        ),
        title="Outcome",
    )
    error_message: str | None = Field(
        None, description="Populated only when outcome='error'.", title="Error Message"
    )
    content_text: str | None = Field(
        None,
        description=(
            "Original natural-language mission description passed to /initiate."
        ),
        title="Content Text",
    )
    agents_negotiating: list[str] | None = Field(
        None,
        description="Agent IDs that participated in this negotiation.",
        title="Agents Negotiating",
    )
    issues: list[str] | None = Field(
        None,
        description="Ordered list of negotiable issue identifiers for this session.",
        title="Issues",
    )
    options_per_issue: dict[str, list[str]] | None = Field(
        None,
        description="Candidate options per issue: {issue_id: [option, ...]}.",
        title="Options Per Issue",
    )
    final_agreement: list[dict[str, Any]] | None = Field(
        None,
        description=(
            "Agreed option per issue: {'issue_id': str, 'chosen_option': str}. None"
            " when the negotiation ended without agreement."
        ),
        title="Final Agreement",
    )


class ResponseType(IntEnum):
    ACCEPT_OFFER = 0
    REJECT_OFFER = 1
    END_NEGOTIATION = 2
    NO_RESPONSE = 3
    WAIT = 4
    LEAVE = 5


class SABOrigin(BaseModel):
    actor_id: str = Field(..., title="Actor Id")
    attestation: str | None = Field(None, title="Attestation")


class SAONMI(BaseModel):
    id: str = Field("", title="Id")
    n_outcomes: int | float = Field(0, title="N Outcomes")
    shared_time_limit: float = Field(1.7976931348623157e308, title="Shared Time Limit")
    shared_n_steps: int | None = Field(None, title="Shared N Steps")
    private_time_limit: float = Field(
        1.7976931348623157e308, title="Private Time Limit"
    )
    private_n_steps: int | None = Field(None, title="Private N Steps")
    pend: float = Field(0.0, title="Pend")
    pend_per_second: float = Field(0.0, title="Pend Per Second")
    step_time_limit: float = Field(1.7976931348623157e308, title="Step Time Limit")
    negotiator_time_limit: float = Field(
        1.7976931348623157e308, title="Negotiator Time Limit"
    )
    dynamic_entry: bool = Field(False, title="Dynamic Entry")
    max_n_negotiators: int | None = Field(None, title="Max N Negotiators")
    annotation: dict[str, Any] | None = Field(None, title="Annotation")
    end_on_no_response: bool = Field(True, title="End On No Response")
    one_offer_per_step: bool = Field(False, title="One Offer Per Step")
    offering_is_accepting: bool = Field(True, title="Offering Is Accepting")
    allow_none_with_data: bool = Field(True, title="Allow None With Data")
    allow_negotiators_to_leave: bool = Field(True, title="Allow Negotiators To Leave")


class SAOResponse(BaseModel):
    response: ResponseType = 3
    outcome: dict[str, Any] | list[Any] | None = Field(None, title="Outcome")
    data: dict[str, Any] | None = Field(None, title="Data")


class NewOffer(RootModel[tuple[str, dict[str, Any] | list[Any] | None]]):
    root: tuple[str, dict[str, Any] | list[Any] | None] = Field(
        ..., max_length=2, min_length=2
    )


class NewDatum(RootModel[tuple[str, dict[str, Any] | None]]):
    root: tuple[str, dict[str, Any] | None] = Field(..., max_length=2, min_length=2)


class SemanticContext(BaseModel):
    schema_version: str = Field("1.0", title="Schema Version")
    encoding: Encoding = Field("json", title="Encoding")


class ThreadState(BaseModel):
    new_offer: dict[str, Any] | list[Any] | None = Field(None, title="New Offer")
    new_data: dict[str, Any] | None = Field(None, title="New Data")
    new_responses: dict[str, ResponseType] | None = Field(None, title="New Responses")
    accepted_offers: list[dict[str, Any] | list[Any] | None] | None = Field(
        None, title="Accepted Offers"
    )


class SABCommitPayloadData(BaseModel):
    message_id: str = Field(..., title="Message Id")
    version: str = Field("0", description="SSTP protocol version.", title="Version")
    dt_created: str = Field(
        ..., description="ISO 8601 creation timestamp.", title="Dt Created"
    )
    origin: SABOrigin
    payload_hash: str = Field(
        ...,
        description="SHA-256 hex digest of the original payload.",
        title="Payload Hash",
    )
    semantic_context: NegotiateCommitSemanticContext


class SABIntentPayloadData(BaseModel):
    message_id: str = Field(..., title="Message Id")
    version: str = Field("0", description="SSTP protocol version.", title="Version")
    dt_created: str = Field(
        ..., description="ISO 8601 creation timestamp.", title="Dt Created"
    )
    origin: SABOrigin
    payload_hash: str = Field(
        ...,
        description="SHA-256 hex digest of the original payload.",
        title="Payload Hash",
    )
    semantic_context: SemanticContext


class SAOState(BaseModel):
    running: bool = Field(False, title="Running")
    waiting: bool = Field(False, title="Waiting")
    started: bool = Field(False, title="Started")
    step: int = Field(0, title="Step")
    time: float = Field(0.0, title="Time")
    relative_time: float = Field(0.0, title="Relative Time")
    broken: bool = Field(False, title="Broken")
    timedout: bool = Field(False, title="Timedout")
    agreement: dict[str, Any] | list[Any] | None = Field(None, title="Agreement")
    results: Any = Field(None, title="Results")
    n_negotiators: int = Field(0, title="N Negotiators")
    has_error: bool = Field(False, title="Has Error")
    error_details: str = Field("", title="Error Details")
    erred_negotiator: str = Field("", title="Erred Negotiator")
    erred_agent: str = Field("", title="Erred Agent")
    threads: dict[str, ThreadState] | None = Field(None, title="Threads")
    last_thread: str = Field("", title="Last Thread")
    left_negotiators: list[str] | None = Field(None, title="Left Negotiators")
    current_offer: dict[str, Any] | list[Any] | None = Field(
        None, title="Current Offer"
    )
    current_proposer: str | None = Field(None, title="Current Proposer")
    current_proposer_agent: str | None = Field(None, title="Current Proposer Agent")
    n_acceptances: int = Field(0, title="N Acceptances")
    new_offers: list[NewOffer] | None = Field(None, title="New Offers")
    new_offerer_agents: list[str | None] | None = Field(
        None, title="New Offerer Agents"
    )
    last_negotiator: str | None = Field(None, title="Last Negotiator")
    current_data: dict[str, Any] | None = Field(None, title="Current Data")
    new_data: list[NewDatum] | None = Field(None, title="New Data")


class NegotiateSemanticContext(BaseModel):
    schema_version: str = Field("1.0", title="Schema Version")
    encoding: Encoding = Field("json", title="Encoding")
    session_id: str = Field(..., title="Session Id")
    issues: list[str] | None = Field(
        None,
        description="Ordered list of negotiable issue identifiers for this session.",
        title="Issues",
    )
    options_per_issue: dict[str, list[str]] | None = Field(
        None,
        description="Candidate options per issue: {issue_id: [option, ...]}.",
        title="Options Per Issue",
    )
    sao_state: SAOState | None = None
    sao_response: SAOResponse | None = None
    nmi: SAONMI | None = None
    offer_validation_failure: dict[str, Any] | None = Field(
        None,
        description=(
            "Set when the previous counter_offer was rejected for unrecognised issue"
            " keys/option values (validation failure, not a strategic reject). Shape:"
            " {rejected_agent_id, round, problems, hint}."
        ),
        title="Offer Validation Failure",
    )


class SABNegotiatePayloadData(BaseModel):
    message_id: str = Field(..., title="Message Id")
    version: str = Field("0", description="SSTP protocol version.", title="Version")
    dt_created: str = Field(
        ..., description="ISO 8601 creation timestamp.", title="Dt Created"
    )
    origin: SABOrigin
    payload_hash: str = Field(
        ...,
        description="SHA-256 hex digest of the original payload.",
        title="Payload Hash",
    )
    semantic_context: NegotiateSemanticContext


class SABPayloadData(
    RootModel[SABCommitPayloadData | SABNegotiatePayloadData | SABIntentPayloadData]
):
    root: SABCommitPayloadData | SABNegotiatePayloadData | SABIntentPayloadData = Field(
        ...,
        description=(
            "Union of the three SAB ``payload.data`` variants.\n\nThis is the root the"
            " schema generator dumps. Variants are discriminated by\nthe shape of"
            " ``semantic_context`` (commit and negotiate carry ``session_id``;\ncommit"
            " additionally carries ``outcome``). Ordered most-constrained first"
            " so\nPydantic's smart-union matching stays unambiguous."
        ),
        title="SABPayloadData",
    )
