# Copyright 2026 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0

# generated by datamodel-codegen:
#   filename:  cip_payload.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class CIPBeliefBlock(BaseModel):
    prior: float = Field(0.5, title="Prior")
    posterior: float = Field(0.5, title="Posterior")
    revision_cause: str | None = Field(None, title="Revision Cause")


class CIPGroundingBlock(BaseModel):
    contingency_verified: bool | None = Field(None, title="Contingency Verified")
    contingency_score: float | None = Field(None, title="Contingency Score")
    repair_reason: str | None = Field(None, title="Repair Reason")
    challenges: list[str] = Field([], title="Challenges")


class CIPUtteranceBlock(BaseModel):
    text: str | None = Field(None, title="Text")
    evidence: list[str] = Field([], title="Evidence")
    addresses_evidence: list[str] = Field([], title="Addresses Evidence")
    turn_depth: int = Field(0, title="Turn Depth")


class CIPMessagePayload(BaseModel):
    utterance: CIPUtteranceBlock = Field(
        {"text": None, "evidence": [], "addresses_evidence": [], "turn_depth": 0},
        validate_default=True,
    )
    grounding: CIPGroundingBlock = Field(
        {
            "contingency_verified": None,
            "contingency_score": None,
            "repair_reason": None,
            "challenges": [],
        },
        validate_default=True,
    )
    belief: CIPBeliefBlock = Field(
        {"prior": 0.5, "posterior": 0.5, "revision_cause": None}, validate_default=True
    )
