#!/usr/bin/env bash

# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# generate.sh — Generate Go types for the IOC L9 schema.
#
# Uses go-jsonschema to produce typed Go structs from the
# canonical IOC L9 JSON schema.
#
# Usage:
#   From project root: ./SSTP/language_bindings/golang/generate.sh
#   From this directory: ./generate.sh
#
# Requirements:
#   go install github.com/atombender/go-jsonschema@latest

set -euo pipefail

# Get the script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Define paths
SCHEMA_FILE="$PROJECT_ROOT/SSTP/spec/l9_schema.json"
OUT_DIR="$SCRIPT_DIR"
PACKAGE="l9"

echo "Generating Go bindings from JSON Schema..."
echo "Schema file: $SCHEMA_FILE"
echo "Output directory: $OUT_DIR"

# Check if schema file exists
if [ ! -f "$SCHEMA_FILE" ]; then
    echo "Error: Schema file not found at $SCHEMA_FILE"
    exit 1
fi

if ! command -v go-jsonschema &>/dev/null; then
  echo "Installing go-jsonschema..."
  go install github.com/atombender/go-jsonschema@latest
fi

echo "Generating Go types from: $SCHEMA_FILE"
$(go env GOPATH)/bin/go-jsonschema \
  --capitalization ID \
  --capitalization URL \
  --package "$PACKAGE" \
  --output "$OUT_DIR/data_model.go" \
  "$SCHEMA_FILE"

# Remove "DO NOT EDIT" line from generated output
sed -i '' '/^\/\/ Code generated by.*DO NOT EDIT\.$/d' "$OUT_DIR/data_model.go"

# Prepend license header
LICENSE_HEADER="// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

"
echo "${LICENSE_HEADER}$(cat "$OUT_DIR/data_model.go")" > "$OUT_DIR/data_model.go"

echo "Running gofmt..."
gofmt -w "$OUT_DIR/data_model.go"

echo "Go bindings generated successfully!"
echo "Generated: $OUT_DIR/data_model.go"
