// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package sab

import "encoding/json"
import "errors"
import "fmt"
import "reflect"

// Semantic context for “kind='commit'“ messages that finalize a negotiation.
type NegotiateCommitSemanticContext struct {
	// Agent IDs that participated in this negotiation.
	AgentsNegotiating *NegotiateCommitSemanticContextAgentsNegotiating `json:"agents_negotiating,omitempty,omitzero" yaml:"agents_negotiating,omitempty" mapstructure:"agents_negotiating,omitempty"`

	// Original natural-language mission description passed to /initiate.
	ContentText interface{} `json:"content_text,omitempty,omitzero" yaml:"content_text,omitempty" mapstructure:"content_text,omitempty"`

	// Encoding corresponds to the JSON schema field "encoding".
	Encoding NegotiateCommitSemanticContextEncoding `json:"encoding,omitempty,omitzero" yaml:"encoding,omitempty" mapstructure:"encoding,omitempty"`

	// Populated only when outcome='error'.
	ErrorMessage interface{} `json:"error_message,omitempty,omitzero" yaml:"error_message,omitempty" mapstructure:"error_message,omitempty"`

	// Agreed option per issue: {'issue_id': str, 'chosen_option': str}. None when the
	// negotiation ended without agreement.
	FinalAgreement *NegotiateCommitSemanticContextFinalAgreement `json:"final_agreement,omitempty,omitzero" yaml:"final_agreement,omitempty" mapstructure:"final_agreement,omitempty"`

	// Ordered list of negotiable issue identifiers for this session.
	Issues []string `json:"issues,omitempty,omitzero" yaml:"issues,omitempty" mapstructure:"issues,omitempty"`

	// Candidate options per issue: {issue_id: [option, ...]}.
	OptionsPerIssue NegotiateCommitSemanticContextOptionsPerIssue `json:"options_per_issue,omitempty,omitzero" yaml:"options_per_issue,omitempty" mapstructure:"options_per_issue,omitempty"`

	// High-level outcome: 'agreement' — consensus reached; 'disagreement' — step
	// budget exhausted; 'broken' — a participant dropped out or returned an invalid
	// offer; 'error' — pipeline exception.
	Outcome string `json:"outcome" yaml:"outcome" mapstructure:"outcome"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion string `json:"schema_version,omitempty,omitzero" yaml:"schema_version,omitempty" mapstructure:"schema_version,omitempty"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id" yaml:"session_id" mapstructure:"session_id"`
}

// Agent IDs that participated in this negotiation.
type NegotiateCommitSemanticContextAgentsNegotiating []string

type NegotiateCommitSemanticContextAgentsNegotiating_0 []string

type NegotiateCommitSemanticContextContentText_0 *string

type NegotiateCommitSemanticContextEncoding string

const NegotiateCommitSemanticContextEncodingHybrid NegotiateCommitSemanticContextEncoding = "hybrid"
const NegotiateCommitSemanticContextEncodingJson NegotiateCommitSemanticContextEncoding = "json"
const NegotiateCommitSemanticContextEncodingStructuredText NegotiateCommitSemanticContextEncoding = "structured_text"

var enumValues_NegotiateCommitSemanticContextEncoding = []interface{}{
	"json",
	"structured_text",
	"hybrid",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateCommitSemanticContextEncoding) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NegotiateCommitSemanticContextEncoding {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NegotiateCommitSemanticContextEncoding, v)
	}
	*j = NegotiateCommitSemanticContextEncoding(v)
	return nil
}

type NegotiateCommitSemanticContextErrorMessage_0 *string

// Agreed option per issue: {'issue_id': str, 'chosen_option': str}. None when the
// negotiation ended without agreement.
type NegotiateCommitSemanticContextFinalAgreement []map[string]interface{}

type NegotiateCommitSemanticContextFinalAgreement_0 []map[string]interface{}

// Candidate options per issue: {issue_id: [option, ...]}.
type NegotiateCommitSemanticContextOptionsPerIssue map[string][]string

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateCommitSemanticContext) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["outcome"]; raw != nil && !ok {
		return fmt.Errorf("field outcome in NegotiateCommitSemanticContext: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in NegotiateCommitSemanticContext: required")
	}
	type Plain NegotiateCommitSemanticContext
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["encoding"]; !ok || v == nil {
		plain.Encoding = "json"
	}
	if v, ok := raw["schema_version"]; !ok || v == nil {
		plain.SchemaVersion = "1.0"
	}
	*j = NegotiateCommitSemanticContext(plain)
	return nil
}

// SAO-specific semantic context for “kind='negotiate'“ messages.
//
// Carries a full NegMAS SAO snapshot so receivers have the mechanism state,
// the latest response, and (optionally) the NMI configuration in one place.
type NegotiateSemanticContext struct {
	// Encoding corresponds to the JSON schema field "encoding".
	Encoding NegotiateSemanticContextEncoding `json:"encoding,omitempty,omitzero" yaml:"encoding,omitempty" mapstructure:"encoding,omitempty"`

	// Ordered list of negotiable issue identifiers for this session.
	Issues []string `json:"issues,omitempty,omitzero" yaml:"issues,omitempty" mapstructure:"issues,omitempty"`

	// Nmi corresponds to the JSON schema field "nmi".
	Nmi *NegotiateSemanticContextNmi `json:"nmi,omitempty,omitzero" yaml:"nmi,omitempty" mapstructure:"nmi,omitempty"`

	// Set when the previous counter_offer was rejected for unrecognised issue
	// keys/option values (validation failure, not a strategic reject). Shape:
	// {rejected_agent_id, round, problems, hint}.
	OfferValidationFailure *NegotiateSemanticContextOfferValidationFailure `json:"offer_validation_failure,omitempty,omitzero" yaml:"offer_validation_failure,omitempty" mapstructure:"offer_validation_failure,omitempty"`

	// Candidate options per issue: {issue_id: [option, ...]}.
	OptionsPerIssue NegotiateSemanticContextOptionsPerIssue `json:"options_per_issue,omitempty,omitzero" yaml:"options_per_issue,omitempty" mapstructure:"options_per_issue,omitempty"`

	// SaoResponse corresponds to the JSON schema field "sao_response".
	SaoResponse *NegotiateSemanticContextSaoResponse `json:"sao_response,omitempty,omitzero" yaml:"sao_response,omitempty" mapstructure:"sao_response,omitempty"`

	// SaoState corresponds to the JSON schema field "sao_state".
	SaoState *NegotiateSemanticContextSaoState `json:"sao_state,omitempty,omitzero" yaml:"sao_state,omitempty" mapstructure:"sao_state,omitempty"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion string `json:"schema_version,omitempty,omitzero" yaml:"schema_version,omitempty" mapstructure:"schema_version,omitempty"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id" yaml:"session_id" mapstructure:"session_id"`
}

type NegotiateSemanticContextEncoding string

const NegotiateSemanticContextEncodingHybrid NegotiateSemanticContextEncoding = "hybrid"
const NegotiateSemanticContextEncodingJson NegotiateSemanticContextEncoding = "json"
const NegotiateSemanticContextEncodingStructuredText NegotiateSemanticContextEncoding = "structured_text"

var enumValues_NegotiateSemanticContextEncoding = []interface{}{
	"json",
	"structured_text",
	"hybrid",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateSemanticContextEncoding) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NegotiateSemanticContextEncoding {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NegotiateSemanticContextEncoding, v)
	}
	*j = NegotiateSemanticContextEncoding(v)
	return nil
}

// NegotiatorMechanismInterface configuration snapshot for SAO.
//
// Omits the internal “_mechanism“ back-reference and the “time_limit“ /
// “n_steps“ computed fields (derived at runtime). All base fields have
// defaults so this can be built from a plain dict / JSON snapshot.
type NegotiateSemanticContextNmi struct {
	// AllowNegotiatorsToLeave corresponds to the JSON schema field
	// "allow_negotiators_to_leave".
	AllowNegotiatorsToLeave bool `json:"allow_negotiators_to_leave,omitempty,omitzero" yaml:"allow_negotiators_to_leave,omitempty" mapstructure:"allow_negotiators_to_leave,omitempty"`

	// AllowNoneWithData corresponds to the JSON schema field "allow_none_with_data".
	AllowNoneWithData bool `json:"allow_none_with_data,omitempty,omitzero" yaml:"allow_none_with_data,omitempty" mapstructure:"allow_none_with_data,omitempty"`

	// Annotation corresponds to the JSON schema field "annotation".
	Annotation SAONMIAnnotation `json:"annotation,omitempty,omitzero" yaml:"annotation,omitempty" mapstructure:"annotation,omitempty"`

	// DynamicEntry corresponds to the JSON schema field "dynamic_entry".
	DynamicEntry bool `json:"dynamic_entry,omitempty,omitzero" yaml:"dynamic_entry,omitempty" mapstructure:"dynamic_entry,omitempty"`

	// EndOnNoResponse corresponds to the JSON schema field "end_on_no_response".
	EndOnNoResponse bool `json:"end_on_no_response,omitempty,omitzero" yaml:"end_on_no_response,omitempty" mapstructure:"end_on_no_response,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id,omitempty,omitzero" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// MaxNNegotiators corresponds to the JSON schema field "max_n_negotiators".
	MaxNNegotiators interface{} `json:"max_n_negotiators,omitempty,omitzero" yaml:"max_n_negotiators,omitempty" mapstructure:"max_n_negotiators,omitempty"`

	// NOutcomes corresponds to the JSON schema field "n_outcomes".
	NOutcomes interface{} `json:"n_outcomes,omitempty,omitzero" yaml:"n_outcomes,omitempty" mapstructure:"n_outcomes,omitempty"`

	// NegotiatorTimeLimit corresponds to the JSON schema field
	// "negotiator_time_limit".
	NegotiatorTimeLimit float64 `json:"negotiator_time_limit,omitempty,omitzero" yaml:"negotiator_time_limit,omitempty" mapstructure:"negotiator_time_limit,omitempty"`

	// OfferingIsAccepting corresponds to the JSON schema field
	// "offering_is_accepting".
	OfferingIsAccepting bool `json:"offering_is_accepting,omitempty,omitzero" yaml:"offering_is_accepting,omitempty" mapstructure:"offering_is_accepting,omitempty"`

	// OneOfferPerStep corresponds to the JSON schema field "one_offer_per_step".
	OneOfferPerStep bool `json:"one_offer_per_step,omitempty,omitzero" yaml:"one_offer_per_step,omitempty" mapstructure:"one_offer_per_step,omitempty"`

	// Pend corresponds to the JSON schema field "pend".
	Pend float64 `json:"pend,omitempty,omitzero" yaml:"pend,omitempty" mapstructure:"pend,omitempty"`

	// PendPerSecond corresponds to the JSON schema field "pend_per_second".
	PendPerSecond float64 `json:"pend_per_second,omitempty,omitzero" yaml:"pend_per_second,omitempty" mapstructure:"pend_per_second,omitempty"`

	// PrivateNSteps corresponds to the JSON schema field "private_n_steps".
	PrivateNSteps interface{} `json:"private_n_steps,omitempty,omitzero" yaml:"private_n_steps,omitempty" mapstructure:"private_n_steps,omitempty"`

	// PrivateTimeLimit corresponds to the JSON schema field "private_time_limit".
	PrivateTimeLimit float64 `json:"private_time_limit,omitempty,omitzero" yaml:"private_time_limit,omitempty" mapstructure:"private_time_limit,omitempty"`

	// SharedNSteps corresponds to the JSON schema field "shared_n_steps".
	SharedNSteps interface{} `json:"shared_n_steps,omitempty,omitzero" yaml:"shared_n_steps,omitempty" mapstructure:"shared_n_steps,omitempty"`

	// SharedTimeLimit corresponds to the JSON schema field "shared_time_limit".
	SharedTimeLimit float64 `json:"shared_time_limit,omitempty,omitzero" yaml:"shared_time_limit,omitempty" mapstructure:"shared_time_limit,omitempty"`

	// StepTimeLimit corresponds to the JSON schema field "step_time_limit".
	StepTimeLimit float64 `json:"step_time_limit,omitempty,omitzero" yaml:"step_time_limit,omitempty" mapstructure:"step_time_limit,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateSemanticContextNmi) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var negotiateSemanticContextNmi_0 NegotiateSemanticContextNmi_0
	var errs []error
	if err := negotiateSemanticContextNmi_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain NegotiateSemanticContextNmi
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NegotiateSemanticContextNmi(plain)
	return nil
}

// Set when the previous counter_offer was rejected for unrecognised issue
// keys/option values (validation failure, not a strategic reject). Shape:
// {rejected_agent_id, round, problems, hint}.
type NegotiateSemanticContextOfferValidationFailure map[string]interface{}

type NegotiateSemanticContextOfferValidationFailure_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateSemanticContextOfferValidationFailure_0) UnmarshalJSON(value []byte) error {
	type Plain NegotiateSemanticContextOfferValidationFailure_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NegotiateSemanticContextOfferValidationFailure_0(plain)
	return nil
}

// Candidate options per issue: {issue_id: [option, ...]}.
type NegotiateSemanticContextOptionsPerIssue map[string][]string

// A single negotiator response in one SAO round.
type NegotiateSemanticContextSaoResponse struct {
	// Data corresponds to the JSON schema field "data".
	Data *NegotiateSemanticContextSaoResponseData `json:"data,omitempty,omitzero" yaml:"data,omitempty" mapstructure:"data,omitempty"`

	// Outcome corresponds to the JSON schema field "outcome".
	Outcome *NegotiateSemanticContextSaoResponseOutcome `json:"outcome,omitempty,omitzero" yaml:"outcome,omitempty" mapstructure:"outcome,omitempty"`

	// Response corresponds to the JSON schema field "response".
	Response ResponseType `json:"response,omitempty,omitzero" yaml:"response,omitempty" mapstructure:"response,omitempty"`
}

type NegotiateSemanticContextSaoResponseData map[string]interface{}

type NegotiateSemanticContextSaoResponseOutcome map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateSemanticContextSaoResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var negotiateSemanticContextSaoResponse_0 NegotiateSemanticContextSaoResponse_0
	var errs []error
	if err := negotiateSemanticContextSaoResponse_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain NegotiateSemanticContextSaoResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NegotiateSemanticContextSaoResponse(plain)
	return nil
}

// Full mechanism state for the Stacked Alternating Offers (SAO) protocol.
type NegotiateSemanticContextSaoState struct {
	// Agreement corresponds to the JSON schema field "agreement".
	Agreement *NegotiateSemanticContextSaoStateAgreement `json:"agreement,omitempty,omitzero" yaml:"agreement,omitempty" mapstructure:"agreement,omitempty"`

	// Broken corresponds to the JSON schema field "broken".
	Broken bool `json:"broken,omitempty,omitzero" yaml:"broken,omitempty" mapstructure:"broken,omitempty"`

	// CurrentData corresponds to the JSON schema field "current_data".
	CurrentData *NegotiateSemanticContextSaoStateCurrentData `json:"current_data,omitempty,omitzero" yaml:"current_data,omitempty" mapstructure:"current_data,omitempty"`

	// CurrentOffer corresponds to the JSON schema field "current_offer".
	CurrentOffer *NegotiateSemanticContextSaoStateCurrentOffer `json:"current_offer,omitempty,omitzero" yaml:"current_offer,omitempty" mapstructure:"current_offer,omitempty"`

	// CurrentProposer corresponds to the JSON schema field "current_proposer".
	CurrentProposer interface{} `json:"current_proposer,omitempty,omitzero" yaml:"current_proposer,omitempty" mapstructure:"current_proposer,omitempty"`

	// CurrentProposerAgent corresponds to the JSON schema field
	// "current_proposer_agent".
	CurrentProposerAgent interface{} `json:"current_proposer_agent,omitempty,omitzero" yaml:"current_proposer_agent,omitempty" mapstructure:"current_proposer_agent,omitempty"`

	// ErredAgent corresponds to the JSON schema field "erred_agent".
	ErredAgent string `json:"erred_agent,omitempty,omitzero" yaml:"erred_agent,omitempty" mapstructure:"erred_agent,omitempty"`

	// ErredNegotiator corresponds to the JSON schema field "erred_negotiator".
	ErredNegotiator string `json:"erred_negotiator,omitempty,omitzero" yaml:"erred_negotiator,omitempty" mapstructure:"erred_negotiator,omitempty"`

	// ErrorDetails corresponds to the JSON schema field "error_details".
	ErrorDetails string `json:"error_details,omitempty,omitzero" yaml:"error_details,omitempty" mapstructure:"error_details,omitempty"`

	// HasError corresponds to the JSON schema field "has_error".
	HasError bool `json:"has_error,omitempty,omitzero" yaml:"has_error,omitempty" mapstructure:"has_error,omitempty"`

	// LastNegotiator corresponds to the JSON schema field "last_negotiator".
	LastNegotiator interface{} `json:"last_negotiator,omitempty,omitzero" yaml:"last_negotiator,omitempty" mapstructure:"last_negotiator,omitempty"`

	// LastThread corresponds to the JSON schema field "last_thread".
	LastThread string `json:"last_thread,omitempty,omitzero" yaml:"last_thread,omitempty" mapstructure:"last_thread,omitempty"`

	// LeftNegotiators corresponds to the JSON schema field "left_negotiators".
	LeftNegotiators []string `json:"left_negotiators,omitempty,omitzero" yaml:"left_negotiators,omitempty" mapstructure:"left_negotiators,omitempty"`

	// NAcceptances corresponds to the JSON schema field "n_acceptances".
	NAcceptances int `json:"n_acceptances,omitempty,omitzero" yaml:"n_acceptances,omitempty" mapstructure:"n_acceptances,omitempty"`

	// NNegotiators corresponds to the JSON schema field "n_negotiators".
	NNegotiators int `json:"n_negotiators,omitempty,omitzero" yaml:"n_negotiators,omitempty" mapstructure:"n_negotiators,omitempty"`

	// NewData corresponds to the JSON schema field "new_data".
	NewData [][]interface{} `json:"new_data,omitempty,omitzero" yaml:"new_data,omitempty" mapstructure:"new_data,omitempty"`

	// NewOffererAgents corresponds to the JSON schema field "new_offerer_agents".
	NewOffererAgents []interface{} `json:"new_offerer_agents,omitempty,omitzero" yaml:"new_offerer_agents,omitempty" mapstructure:"new_offerer_agents,omitempty"`

	// NewOffers corresponds to the JSON schema field "new_offers".
	NewOffers [][]interface{} `json:"new_offers,omitempty,omitzero" yaml:"new_offers,omitempty" mapstructure:"new_offers,omitempty"`

	// RelativeTime corresponds to the JSON schema field "relative_time".
	RelativeTime float64 `json:"relative_time,omitempty,omitzero" yaml:"relative_time,omitempty" mapstructure:"relative_time,omitempty"`

	// Results corresponds to the JSON schema field "results".
	Results interface{} `json:"results,omitempty,omitzero" yaml:"results,omitempty" mapstructure:"results,omitempty"`

	// Running corresponds to the JSON schema field "running".
	Running bool `json:"running,omitempty,omitzero" yaml:"running,omitempty" mapstructure:"running,omitempty"`

	// Started corresponds to the JSON schema field "started".
	Started bool `json:"started,omitempty,omitzero" yaml:"started,omitempty" mapstructure:"started,omitempty"`

	// Step corresponds to the JSON schema field "step".
	Step int `json:"step,omitempty,omitzero" yaml:"step,omitempty" mapstructure:"step,omitempty"`

	// Threads corresponds to the JSON schema field "threads".
	Threads SAOStateThreads `json:"threads,omitempty,omitzero" yaml:"threads,omitempty" mapstructure:"threads,omitempty"`

	// Time corresponds to the JSON schema field "time".
	Time float64 `json:"time,omitempty,omitzero" yaml:"time,omitempty" mapstructure:"time,omitempty"`

	// Timedout corresponds to the JSON schema field "timedout".
	Timedout bool `json:"timedout,omitempty,omitzero" yaml:"timedout,omitempty" mapstructure:"timedout,omitempty"`

	// Waiting corresponds to the JSON schema field "waiting".
	Waiting bool `json:"waiting,omitempty,omitzero" yaml:"waiting,omitempty" mapstructure:"waiting,omitempty"`
}

type NegotiateSemanticContextSaoStateAgreement map[string]interface{}

type NegotiateSemanticContextSaoStateCurrentData map[string]interface{}

type NegotiateSemanticContextSaoStateCurrentOffer map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateSemanticContextSaoState) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var negotiateSemanticContextSaoState_0 NegotiateSemanticContextSaoState_0
	var errs []error
	if err := negotiateSemanticContextSaoState_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain NegotiateSemanticContextSaoState
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NegotiateSemanticContextSaoState(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateSemanticContext) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in NegotiateSemanticContext: required")
	}
	type Plain NegotiateSemanticContext
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["encoding"]; !ok || v == nil {
		plain.Encoding = "json"
	}
	if v, ok := raw["schema_version"]; !ok || v == nil {
		plain.SchemaVersion = "1.0"
	}
	*j = NegotiateSemanticContext(plain)
	return nil
}

type ResponseType int

var enumValues_ResponseType = []interface{}{
	0,
	1,
	2,
	3,
	4,
	5,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResponseType) UnmarshalJSON(value []byte) error {
	var v int
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ResponseType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ResponseType, v)
	}
	*j = ResponseType(v)
	return nil
}

// “payload.data“ when the wrapped SSTP message is kind=commit.
type SABCommitPayloadData struct {
	// ISO 8601 creation timestamp.
	DtCreated string `json:"dt_created" yaml:"dt_created" mapstructure:"dt_created"`

	// MessageID corresponds to the JSON schema field "message_id".
	MessageID string `json:"message_id" yaml:"message_id" mapstructure:"message_id"`

	// Origin corresponds to the JSON schema field "origin".
	Origin SABOrigin `json:"origin" yaml:"origin" mapstructure:"origin"`

	// SHA-256 hex digest of the original payload.
	PayloadHash string `json:"payload_hash" yaml:"payload_hash" mapstructure:"payload_hash"`

	// SemanticContext corresponds to the JSON schema field "semantic_context".
	SemanticContext NegotiateCommitSemanticContext `json:"semantic_context" yaml:"semantic_context" mapstructure:"semantic_context"`

	// SSTP protocol version.
	Version string `json:"version,omitempty,omitzero" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABCommitPayloadData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dt_created"]; raw != nil && !ok {
		return fmt.Errorf("field dt_created in SABCommitPayloadData: required")
	}
	if _, ok := raw["message_id"]; raw != nil && !ok {
		return fmt.Errorf("field message_id in SABCommitPayloadData: required")
	}
	if _, ok := raw["origin"]; raw != nil && !ok {
		return fmt.Errorf("field origin in SABCommitPayloadData: required")
	}
	if _, ok := raw["payload_hash"]; raw != nil && !ok {
		return fmt.Errorf("field payload_hash in SABCommitPayloadData: required")
	}
	if _, ok := raw["semantic_context"]; raw != nil && !ok {
		return fmt.Errorf("field semantic_context in SABCommitPayloadData: required")
	}
	type Plain SABCommitPayloadData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["version"]; !ok || v == nil {
		plain.Version = "0"
	}
	*j = SABCommitPayloadData(plain)
	return nil
}

// “payload.data“ when the wrapped SSTP message is kind=intent.
type SABIntentPayloadData struct {
	// ISO 8601 creation timestamp.
	DtCreated string `json:"dt_created" yaml:"dt_created" mapstructure:"dt_created"`

	// MessageID corresponds to the JSON schema field "message_id".
	MessageID string `json:"message_id" yaml:"message_id" mapstructure:"message_id"`

	// Origin corresponds to the JSON schema field "origin".
	Origin SABOrigin `json:"origin" yaml:"origin" mapstructure:"origin"`

	// SHA-256 hex digest of the original payload.
	PayloadHash string `json:"payload_hash" yaml:"payload_hash" mapstructure:"payload_hash"`

	// SemanticContext corresponds to the JSON schema field "semantic_context".
	SemanticContext SemanticContext `json:"semantic_context" yaml:"semantic_context" mapstructure:"semantic_context"`

	// SSTP protocol version.
	Version string `json:"version,omitempty,omitzero" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABIntentPayloadData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dt_created"]; raw != nil && !ok {
		return fmt.Errorf("field dt_created in SABIntentPayloadData: required")
	}
	if _, ok := raw["message_id"]; raw != nil && !ok {
		return fmt.Errorf("field message_id in SABIntentPayloadData: required")
	}
	if _, ok := raw["origin"]; raw != nil && !ok {
		return fmt.Errorf("field origin in SABIntentPayloadData: required")
	}
	if _, ok := raw["payload_hash"]; raw != nil && !ok {
		return fmt.Errorf("field payload_hash in SABIntentPayloadData: required")
	}
	if _, ok := raw["semantic_context"]; raw != nil && !ok {
		return fmt.Errorf("field semantic_context in SABIntentPayloadData: required")
	}
	type Plain SABIntentPayloadData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["version"]; !ok || v == nil {
		plain.Version = "0"
	}
	*j = SABIntentPayloadData(plain)
	return nil
}

// “payload.data“ when the wrapped SSTP message is kind=negotiate.
type SABNegotiatePayloadData struct {
	// ISO 8601 creation timestamp.
	DtCreated string `json:"dt_created" yaml:"dt_created" mapstructure:"dt_created"`

	// MessageID corresponds to the JSON schema field "message_id".
	MessageID string `json:"message_id" yaml:"message_id" mapstructure:"message_id"`

	// Origin corresponds to the JSON schema field "origin".
	Origin SABOrigin `json:"origin" yaml:"origin" mapstructure:"origin"`

	// SHA-256 hex digest of the original payload.
	PayloadHash string `json:"payload_hash" yaml:"payload_hash" mapstructure:"payload_hash"`

	// SemanticContext corresponds to the JSON schema field "semantic_context".
	SemanticContext NegotiateSemanticContext `json:"semantic_context" yaml:"semantic_context" mapstructure:"semantic_context"`

	// SSTP protocol version.
	Version string `json:"version,omitempty,omitzero" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABNegotiatePayloadData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dt_created"]; raw != nil && !ok {
		return fmt.Errorf("field dt_created in SABNegotiatePayloadData: required")
	}
	if _, ok := raw["message_id"]; raw != nil && !ok {
		return fmt.Errorf("field message_id in SABNegotiatePayloadData: required")
	}
	if _, ok := raw["origin"]; raw != nil && !ok {
		return fmt.Errorf("field origin in SABNegotiatePayloadData: required")
	}
	if _, ok := raw["payload_hash"]; raw != nil && !ok {
		return fmt.Errorf("field payload_hash in SABNegotiatePayloadData: required")
	}
	if _, ok := raw["semantic_context"]; raw != nil && !ok {
		return fmt.Errorf("field semantic_context in SABNegotiatePayloadData: required")
	}
	type Plain SABNegotiatePayloadData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["version"]; !ok || v == nil {
		plain.Version = "0"
	}
	*j = SABNegotiatePayloadData(plain)
	return nil
}

// Who produced this message (tenant_id is not carried at the L9 layer).
type SABOrigin struct {
	// ActorID corresponds to the JSON schema field "actor_id".
	ActorID string `json:"actor_id" yaml:"actor_id" mapstructure:"actor_id"`

	// Attestation corresponds to the JSON schema field "attestation".
	Attestation interface{} `json:"attestation,omitempty,omitzero" yaml:"attestation,omitempty" mapstructure:"attestation,omitempty"`
}

type SABOriginAttestation_0 *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABOrigin) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["actor_id"]; raw != nil && !ok {
		return fmt.Errorf("field actor_id in SABOrigin: required")
	}
	type Plain SABOrigin
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SABOrigin(plain)
	return nil
}

// NegotiatorMechanismInterface configuration snapshot for SAO.
//
// Omits the internal “_mechanism“ back-reference and the “time_limit“ /
// “n_steps“ computed fields (derived at runtime). All base fields have
// defaults so this can be built from a plain dict / JSON snapshot.
type SAONMI struct {
	// AllowNegotiatorsToLeave corresponds to the JSON schema field
	// "allow_negotiators_to_leave".
	AllowNegotiatorsToLeave bool `json:"allow_negotiators_to_leave,omitempty,omitzero" yaml:"allow_negotiators_to_leave,omitempty" mapstructure:"allow_negotiators_to_leave,omitempty"`

	// AllowNoneWithData corresponds to the JSON schema field "allow_none_with_data".
	AllowNoneWithData bool `json:"allow_none_with_data,omitempty,omitzero" yaml:"allow_none_with_data,omitempty" mapstructure:"allow_none_with_data,omitempty"`

	// Annotation corresponds to the JSON schema field "annotation".
	Annotation SAONMIAnnotation `json:"annotation,omitempty,omitzero" yaml:"annotation,omitempty" mapstructure:"annotation,omitempty"`

	// DynamicEntry corresponds to the JSON schema field "dynamic_entry".
	DynamicEntry bool `json:"dynamic_entry,omitempty,omitzero" yaml:"dynamic_entry,omitempty" mapstructure:"dynamic_entry,omitempty"`

	// EndOnNoResponse corresponds to the JSON schema field "end_on_no_response".
	EndOnNoResponse bool `json:"end_on_no_response,omitempty,omitzero" yaml:"end_on_no_response,omitempty" mapstructure:"end_on_no_response,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id,omitempty,omitzero" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// MaxNNegotiators corresponds to the JSON schema field "max_n_negotiators".
	MaxNNegotiators interface{} `json:"max_n_negotiators,omitempty,omitzero" yaml:"max_n_negotiators,omitempty" mapstructure:"max_n_negotiators,omitempty"`

	// NOutcomes corresponds to the JSON schema field "n_outcomes".
	NOutcomes interface{} `json:"n_outcomes,omitempty,omitzero" yaml:"n_outcomes,omitempty" mapstructure:"n_outcomes,omitempty"`

	// NegotiatorTimeLimit corresponds to the JSON schema field
	// "negotiator_time_limit".
	NegotiatorTimeLimit float64 `json:"negotiator_time_limit,omitempty,omitzero" yaml:"negotiator_time_limit,omitempty" mapstructure:"negotiator_time_limit,omitempty"`

	// OfferingIsAccepting corresponds to the JSON schema field
	// "offering_is_accepting".
	OfferingIsAccepting bool `json:"offering_is_accepting,omitempty,omitzero" yaml:"offering_is_accepting,omitempty" mapstructure:"offering_is_accepting,omitempty"`

	// OneOfferPerStep corresponds to the JSON schema field "one_offer_per_step".
	OneOfferPerStep bool `json:"one_offer_per_step,omitempty,omitzero" yaml:"one_offer_per_step,omitempty" mapstructure:"one_offer_per_step,omitempty"`

	// Pend corresponds to the JSON schema field "pend".
	Pend float64 `json:"pend,omitempty,omitzero" yaml:"pend,omitempty" mapstructure:"pend,omitempty"`

	// PendPerSecond corresponds to the JSON schema field "pend_per_second".
	PendPerSecond float64 `json:"pend_per_second,omitempty,omitzero" yaml:"pend_per_second,omitempty" mapstructure:"pend_per_second,omitempty"`

	// PrivateNSteps corresponds to the JSON schema field "private_n_steps".
	PrivateNSteps interface{} `json:"private_n_steps,omitempty,omitzero" yaml:"private_n_steps,omitempty" mapstructure:"private_n_steps,omitempty"`

	// PrivateTimeLimit corresponds to the JSON schema field "private_time_limit".
	PrivateTimeLimit float64 `json:"private_time_limit,omitempty,omitzero" yaml:"private_time_limit,omitempty" mapstructure:"private_time_limit,omitempty"`

	// SharedNSteps corresponds to the JSON schema field "shared_n_steps".
	SharedNSteps interface{} `json:"shared_n_steps,omitempty,omitzero" yaml:"shared_n_steps,omitempty" mapstructure:"shared_n_steps,omitempty"`

	// SharedTimeLimit corresponds to the JSON schema field "shared_time_limit".
	SharedTimeLimit float64 `json:"shared_time_limit,omitempty,omitzero" yaml:"shared_time_limit,omitempty" mapstructure:"shared_time_limit,omitempty"`

	// StepTimeLimit corresponds to the JSON schema field "step_time_limit".
	StepTimeLimit float64 `json:"step_time_limit,omitempty,omitzero" yaml:"step_time_limit,omitempty" mapstructure:"step_time_limit,omitempty"`
}

type SAONMIAnnotation map[string]interface{}

type SAONMIMaxNNegotiators_0 *int

type SAONMIPrivateNSteps_0 *int

type SAONMISharedNSteps_0 *int

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAONMI) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain SAONMI
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allow_negotiators_to_leave"]; !ok || v == nil {
		plain.AllowNegotiatorsToLeave = true
	}
	if v, ok := raw["allow_none_with_data"]; !ok || v == nil {
		plain.AllowNoneWithData = true
	}
	if v, ok := raw["dynamic_entry"]; !ok || v == nil {
		plain.DynamicEntry = false
	}
	if v, ok := raw["end_on_no_response"]; !ok || v == nil {
		plain.EndOnNoResponse = true
	}
	if v, ok := raw["id"]; !ok || v == nil {
		plain.ID = ""
	}
	if v, ok := raw["n_outcomes"]; !ok || v == nil {
		plain.NOutcomes = 0.0
	}
	if v, ok := raw["negotiator_time_limit"]; !ok || v == nil {
		plain.NegotiatorTimeLimit = 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0
	}
	if v, ok := raw["offering_is_accepting"]; !ok || v == nil {
		plain.OfferingIsAccepting = true
	}
	if v, ok := raw["one_offer_per_step"]; !ok || v == nil {
		plain.OneOfferPerStep = false
	}
	if v, ok := raw["pend"]; !ok || v == nil {
		plain.Pend = 0.0
	}
	if v, ok := raw["pend_per_second"]; !ok || v == nil {
		plain.PendPerSecond = 0.0
	}
	if v, ok := raw["private_time_limit"]; !ok || v == nil {
		plain.PrivateTimeLimit = 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0
	}
	if v, ok := raw["shared_time_limit"]; !ok || v == nil {
		plain.SharedTimeLimit = 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0
	}
	if v, ok := raw["step_time_limit"]; !ok || v == nil {
		plain.StepTimeLimit = 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0
	}
	*j = SAONMI(plain)
	return nil
}

// A single negotiator response in one SAO round.
type SAOResponse struct {
	// Data corresponds to the JSON schema field "data".
	Data *SAOResponseData `json:"data,omitempty,omitzero" yaml:"data,omitempty" mapstructure:"data,omitempty"`

	// Outcome corresponds to the JSON schema field "outcome".
	Outcome *SAOResponseOutcome `json:"outcome,omitempty,omitzero" yaml:"outcome,omitempty" mapstructure:"outcome,omitempty"`

	// Response corresponds to the JSON schema field "response".
	Response ResponseType `json:"response,omitempty,omitzero" yaml:"response,omitempty" mapstructure:"response,omitempty"`
}

type SAOResponseData map[string]interface{}

type SAOResponseData_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOResponseData_0) UnmarshalJSON(value []byte) error {
	type Plain SAOResponseData_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SAOResponseData_0(plain)
	return nil
}

type SAOResponseOutcome map[string]interface{}

type SAOResponseOutcome_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOResponseOutcome_0) UnmarshalJSON(value []byte) error {
	type Plain SAOResponseOutcome_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SAOResponseOutcome_0(plain)
	return nil
}

type SAOResponseOutcome_1 []interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain SAOResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["response"]; !ok || v == nil {
		plain.Response = 3
	}
	*j = SAOResponse(plain)
	return nil
}

// Full mechanism state for the Stacked Alternating Offers (SAO) protocol.
type SAOState struct {
	// Agreement corresponds to the JSON schema field "agreement".
	Agreement *SAOStateAgreement `json:"agreement,omitempty,omitzero" yaml:"agreement,omitempty" mapstructure:"agreement,omitempty"`

	// Broken corresponds to the JSON schema field "broken".
	Broken bool `json:"broken,omitempty,omitzero" yaml:"broken,omitempty" mapstructure:"broken,omitempty"`

	// CurrentData corresponds to the JSON schema field "current_data".
	CurrentData *SAOStateCurrentData `json:"current_data,omitempty,omitzero" yaml:"current_data,omitempty" mapstructure:"current_data,omitempty"`

	// CurrentOffer corresponds to the JSON schema field "current_offer".
	CurrentOffer *SAOStateCurrentOffer `json:"current_offer,omitempty,omitzero" yaml:"current_offer,omitempty" mapstructure:"current_offer,omitempty"`

	// CurrentProposer corresponds to the JSON schema field "current_proposer".
	CurrentProposer interface{} `json:"current_proposer,omitempty,omitzero" yaml:"current_proposer,omitempty" mapstructure:"current_proposer,omitempty"`

	// CurrentProposerAgent corresponds to the JSON schema field
	// "current_proposer_agent".
	CurrentProposerAgent interface{} `json:"current_proposer_agent,omitempty,omitzero" yaml:"current_proposer_agent,omitempty" mapstructure:"current_proposer_agent,omitempty"`

	// ErredAgent corresponds to the JSON schema field "erred_agent".
	ErredAgent string `json:"erred_agent,omitempty,omitzero" yaml:"erred_agent,omitempty" mapstructure:"erred_agent,omitempty"`

	// ErredNegotiator corresponds to the JSON schema field "erred_negotiator".
	ErredNegotiator string `json:"erred_negotiator,omitempty,omitzero" yaml:"erred_negotiator,omitempty" mapstructure:"erred_negotiator,omitempty"`

	// ErrorDetails corresponds to the JSON schema field "error_details".
	ErrorDetails string `json:"error_details,omitempty,omitzero" yaml:"error_details,omitempty" mapstructure:"error_details,omitempty"`

	// HasError corresponds to the JSON schema field "has_error".
	HasError bool `json:"has_error,omitempty,omitzero" yaml:"has_error,omitempty" mapstructure:"has_error,omitempty"`

	// LastNegotiator corresponds to the JSON schema field "last_negotiator".
	LastNegotiator interface{} `json:"last_negotiator,omitempty,omitzero" yaml:"last_negotiator,omitempty" mapstructure:"last_negotiator,omitempty"`

	// LastThread corresponds to the JSON schema field "last_thread".
	LastThread string `json:"last_thread,omitempty,omitzero" yaml:"last_thread,omitempty" mapstructure:"last_thread,omitempty"`

	// LeftNegotiators corresponds to the JSON schema field "left_negotiators".
	LeftNegotiators []string `json:"left_negotiators,omitempty,omitzero" yaml:"left_negotiators,omitempty" mapstructure:"left_negotiators,omitempty"`

	// NAcceptances corresponds to the JSON schema field "n_acceptances".
	NAcceptances int `json:"n_acceptances,omitempty,omitzero" yaml:"n_acceptances,omitempty" mapstructure:"n_acceptances,omitempty"`

	// NNegotiators corresponds to the JSON schema field "n_negotiators".
	NNegotiators int `json:"n_negotiators,omitempty,omitzero" yaml:"n_negotiators,omitempty" mapstructure:"n_negotiators,omitempty"`

	// NewData corresponds to the JSON schema field "new_data".
	NewData [][]interface{} `json:"new_data,omitempty,omitzero" yaml:"new_data,omitempty" mapstructure:"new_data,omitempty"`

	// NewOffererAgents corresponds to the JSON schema field "new_offerer_agents".
	NewOffererAgents []interface{} `json:"new_offerer_agents,omitempty,omitzero" yaml:"new_offerer_agents,omitempty" mapstructure:"new_offerer_agents,omitempty"`

	// NewOffers corresponds to the JSON schema field "new_offers".
	NewOffers [][]interface{} `json:"new_offers,omitempty,omitzero" yaml:"new_offers,omitempty" mapstructure:"new_offers,omitempty"`

	// RelativeTime corresponds to the JSON schema field "relative_time".
	RelativeTime float64 `json:"relative_time,omitempty,omitzero" yaml:"relative_time,omitempty" mapstructure:"relative_time,omitempty"`

	// Results corresponds to the JSON schema field "results".
	Results interface{} `json:"results,omitempty,omitzero" yaml:"results,omitempty" mapstructure:"results,omitempty"`

	// Running corresponds to the JSON schema field "running".
	Running bool `json:"running,omitempty,omitzero" yaml:"running,omitempty" mapstructure:"running,omitempty"`

	// Started corresponds to the JSON schema field "started".
	Started bool `json:"started,omitempty,omitzero" yaml:"started,omitempty" mapstructure:"started,omitempty"`

	// Step corresponds to the JSON schema field "step".
	Step int `json:"step,omitempty,omitzero" yaml:"step,omitempty" mapstructure:"step,omitempty"`

	// Threads corresponds to the JSON schema field "threads".
	Threads SAOStateThreads `json:"threads,omitempty,omitzero" yaml:"threads,omitempty" mapstructure:"threads,omitempty"`

	// Time corresponds to the JSON schema field "time".
	Time float64 `json:"time,omitempty,omitzero" yaml:"time,omitempty" mapstructure:"time,omitempty"`

	// Timedout corresponds to the JSON schema field "timedout".
	Timedout bool `json:"timedout,omitempty,omitzero" yaml:"timedout,omitempty" mapstructure:"timedout,omitempty"`

	// Waiting corresponds to the JSON schema field "waiting".
	Waiting bool `json:"waiting,omitempty,omitzero" yaml:"waiting,omitempty" mapstructure:"waiting,omitempty"`
}

type SAOStateAgreement map[string]interface{}

type SAOStateAgreement_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOStateAgreement_0) UnmarshalJSON(value []byte) error {
	type Plain SAOStateAgreement_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SAOStateAgreement_0(plain)
	return nil
}

type SAOStateAgreement_1 []interface{}

type SAOStateCurrentData map[string]interface{}

type SAOStateCurrentData_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOStateCurrentData_0) UnmarshalJSON(value []byte) error {
	type Plain SAOStateCurrentData_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SAOStateCurrentData_0(plain)
	return nil
}

type SAOStateCurrentOffer map[string]interface{}

type SAOStateCurrentOffer_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOStateCurrentOffer_0) UnmarshalJSON(value []byte) error {
	type Plain SAOStateCurrentOffer_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SAOStateCurrentOffer_0(plain)
	return nil
}

type SAOStateCurrentOffer_1 []interface{}

type SAOStateCurrentProposerAgent_0 *string

type SAOStateCurrentProposer_0 *string

type SAOStateLastNegotiator_0 *string

type SAOStateNewOffererAgentsElem_0 *string

type SAOStateThreads map[string]ThreadState

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOState) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain SAOState
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["broken"]; !ok || v == nil {
		plain.Broken = false
	}
	if v, ok := raw["erred_agent"]; !ok || v == nil {
		plain.ErredAgent = ""
	}
	if v, ok := raw["erred_negotiator"]; !ok || v == nil {
		plain.ErredNegotiator = ""
	}
	if v, ok := raw["error_details"]; !ok || v == nil {
		plain.ErrorDetails = ""
	}
	if v, ok := raw["has_error"]; !ok || v == nil {
		plain.HasError = false
	}
	if v, ok := raw["last_thread"]; !ok || v == nil {
		plain.LastThread = ""
	}
	if v, ok := raw["n_acceptances"]; !ok || v == nil {
		plain.NAcceptances = 0
	}
	if v, ok := raw["n_negotiators"]; !ok || v == nil {
		plain.NNegotiators = 0
	}
	if v, ok := raw["relative_time"]; !ok || v == nil {
		plain.RelativeTime = 0.0
	}
	if v, ok := raw["running"]; !ok || v == nil {
		plain.Running = false
	}
	if v, ok := raw["started"]; !ok || v == nil {
		plain.Started = false
	}
	if v, ok := raw["step"]; !ok || v == nil {
		plain.Step = 0
	}
	if v, ok := raw["time"]; !ok || v == nil {
		plain.Time = 0.0
	}
	if v, ok := raw["timedout"]; !ok || v == nil {
		plain.Timedout = false
	}
	if v, ok := raw["waiting"]; !ok || v == nil {
		plain.Waiting = false
	}
	*j = SAOState(plain)
	return nil
}

// Schema/encoding metadata for a plain (intent) payload.
type SemanticContext struct {
	// Encoding corresponds to the JSON schema field "encoding".
	Encoding SemanticContextEncoding `json:"encoding,omitempty,omitzero" yaml:"encoding,omitempty" mapstructure:"encoding,omitempty"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion string `json:"schema_version,omitempty,omitzero" yaml:"schema_version,omitempty" mapstructure:"schema_version,omitempty"`
}

type SemanticContextEncoding string

const SemanticContextEncodingHybrid SemanticContextEncoding = "hybrid"
const SemanticContextEncodingJson SemanticContextEncoding = "json"
const SemanticContextEncodingStructuredText SemanticContextEncoding = "structured_text"

var enumValues_SemanticContextEncoding = []interface{}{
	"json",
	"structured_text",
	"hybrid",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SemanticContextEncoding) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SemanticContextEncoding {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SemanticContextEncoding, v)
	}
	*j = SemanticContextEncoding(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SemanticContext) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain SemanticContext
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["encoding"]; !ok || v == nil {
		plain.Encoding = "json"
	}
	if v, ok := raw["schema_version"]; !ok || v == nil {
		plain.SchemaVersion = "1.0"
	}
	*j = SemanticContext(plain)
	return nil
}

// Per-thread state in a GB (Generalized Bargaining) round.
type ThreadState struct {
	// AcceptedOffers corresponds to the JSON schema field "accepted_offers".
	AcceptedOffers []*ThreadStateAcceptedOffersElem `json:"accepted_offers,omitempty,omitzero" yaml:"accepted_offers,omitempty" mapstructure:"accepted_offers,omitempty"`

	// NewData corresponds to the JSON schema field "new_data".
	NewData *ThreadStateNewData `json:"new_data,omitempty,omitzero" yaml:"new_data,omitempty" mapstructure:"new_data,omitempty"`

	// NewOffer corresponds to the JSON schema field "new_offer".
	NewOffer *ThreadStateNewOffer `json:"new_offer,omitempty,omitzero" yaml:"new_offer,omitempty" mapstructure:"new_offer,omitempty"`

	// NewResponses corresponds to the JSON schema field "new_responses".
	NewResponses ThreadStateNewResponses `json:"new_responses,omitempty,omitzero" yaml:"new_responses,omitempty" mapstructure:"new_responses,omitempty"`
}

type ThreadStateAcceptedOffersElem map[string]interface{}

type ThreadStateAcceptedOffersElem_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ThreadStateAcceptedOffersElem_0) UnmarshalJSON(value []byte) error {
	type Plain ThreadStateAcceptedOffersElem_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ThreadStateAcceptedOffersElem_0(plain)
	return nil
}

type ThreadStateAcceptedOffersElem_1 []interface{}

type ThreadStateNewData map[string]interface{}

type ThreadStateNewData_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ThreadStateNewData_0) UnmarshalJSON(value []byte) error {
	type Plain ThreadStateNewData_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ThreadStateNewData_0(plain)
	return nil
}

type ThreadStateNewOffer map[string]interface{}

type ThreadStateNewOffer_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ThreadStateNewOffer_0) UnmarshalJSON(value []byte) error {
	type Plain ThreadStateNewOffer_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ThreadStateNewOffer_0(plain)
	return nil
}

type ThreadStateNewOffer_1 []interface{}

type NegotiateSemanticContextSaoState_0 = SAOState

type ThreadStateNewResponses map[string]ResponseType

type NegotiateSemanticContextSaoResponse_0 = SAOResponse

type NegotiateSemanticContextNmi_0 = SAONMI
