// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package sab

import "encoding/json"
import "errors"
import "fmt"
import "reflect"

// A participant in a protocol exchange - can be a human, an AI agent, or a system.
// Multiple actors are listed in L9Header.actors to identify sender(s) and
// receiver(s).
type Actor struct {
	// Attestation corresponds to the JSON schema field "attestation".
	Attestation interface{} `json:"attestation,omitempty,omitzero" yaml:"attestation,omitempty" mapstructure:"attestation,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id" mapstructure:"id"`

	// Role corresponds to the JSON schema field "role".
	Role string `json:"role" yaml:"role" mapstructure:"role"`
}

type ActorAttestation_0 *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Actor) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Actor: required")
	}
	if _, ok := raw["role"]; raw != nil && !ok {
		return fmt.Errorf("field role in Actor: required")
	}
	type Plain Actor
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Actor(plain)
	return nil
}

type Context struct {
	// Epistemic corresponds to the JSON schema field "epistemic".
	Epistemic *ContextEpistemic `json:"epistemic,omitempty,omitzero" yaml:"epistemic,omitempty" mapstructure:"epistemic,omitempty"`

	// Semantic corresponds to the JSON schema field "semantic".
	Semantic *ContextSemantic `json:"semantic,omitempty,omitzero" yaml:"semantic,omitempty" mapstructure:"semantic,omitempty"`

	// Topic corresponds to the JSON schema field "topic".
	Topic string `json:"topic" yaml:"topic" mapstructure:"topic"`
}

// Agent epistemic (belief/knowledge) state at the time the message was sent.
// Currently a placeholder - fields will be added as the model is defined.
type ContextEpistemic map[string]interface{}

// Describes the semantic/ontological framework needed to correctly interpret the
// payload.
// The CFN routing layer uses this to select appropriate cognitive engines (CEs).
type ContextSemantic struct {
	// OntologyRef corresponds to the JSON schema field "ontology_ref".
	OntologyRef string `json:"ontology_ref" yaml:"ontology_ref" mapstructure:"ontology_ref"`

	// Provenance corresponds to the JSON schema field "provenance".
	Provenance *ContextSemanticProvenance `json:"provenance,omitempty,omitzero" yaml:"provenance,omitempty" mapstructure:"provenance,omitempty"`

	// SchemaID corresponds to the JSON schema field "schema_id".
	SchemaID string `json:"schema_id" yaml:"schema_id" mapstructure:"schema_id"`
}

// Tracks the origin and lineage of a message - who created it, from what source,
// and through which transformations. Fields TBD.
type ContextSemanticProvenance map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ContextSemantic) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var contextSemantic_0 ContextSemantic_0
	var errs []error
	if err := contextSemantic_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain ContextSemantic
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ContextSemantic(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Context) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["topic"]; raw != nil && !ok {
		return fmt.Errorf("field topic in Context: required")
	}
	type Plain Context
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Context(plain)
	return nil
}

// Agent epistemic (belief/knowledge) state at the time the message was sent.
// Currently a placeholder - fields will be added as the model is defined.
type Epistemic map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Epistemic) UnmarshalJSON(value []byte) error {
	type Plain Epistemic
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Epistemic(plain)
	return nil
}

// Represents a message in the protocol.
type Message struct {
	// Episode corresponds to the JSON schema field "episode".
	Episode string `json:"episode" yaml:"episode" mapstructure:"episode"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id" mapstructure:"id"`

	// Parents corresponds to the JSON schema field "parents".
	// Ordered list of parent message IDs. Empty list for root messages.
	Parents []string `json:"parents" yaml:"parents" mapstructure:"parents"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Message) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["episode"]; raw != nil && !ok {
		return fmt.Errorf("field episode in Message: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Message: required")
	}
	if _, ok := raw["parents"]; raw != nil && !ok {
		return fmt.Errorf("field parents in Message: required")
	}
	type Plain Message
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Message(plain)
	return nil
}

// Semantic context for “kind='commit'“ messages that finalize a negotiation.
//
// Carries the schema identity of the commit plus the “final_agreement“
// so consumers can inspect the outcome directly from the envelope without
// having to parse the full “payload“.
type NegotiateCommitSemanticContext struct {
	// List of agent IDs that participated in this negotiation.
	AgentsNegotiating *NegotiateCommitSemanticContextAgentsNegotiating `json:"agents_negotiating,omitempty,omitzero" yaml:"agents_negotiating,omitempty" mapstructure:"agents_negotiating,omitempty"`

	// Original natural-language mission description passed to /initiate.
	ContentText interface{} `json:"content_text,omitempty,omitzero" yaml:"content_text,omitempty" mapstructure:"content_text,omitempty"`

	// Encoding corresponds to the JSON schema field "encoding".
	Encoding NegotiateCommitSemanticContextEncoding `json:"encoding,omitempty,omitzero" yaml:"encoding,omitempty" mapstructure:"encoding,omitempty"`

	// Populated only when outcome='error'. Human-readable exception summary.
	ErrorMessage interface{} `json:"error_message,omitempty,omitzero" yaml:"error_message,omitempty" mapstructure:"error_message,omitempty"`

	// Agreed option per issue. Each entry is {'issue_id': str, 'chosen_option': str}.
	// None when negotiation ended without agreement.
	FinalAgreement *NegotiateCommitSemanticContextFinalAgreement `json:"final_agreement,omitempty,omitzero" yaml:"final_agreement,omitempty" mapstructure:"final_agreement,omitempty"`

	// High-level outcome of the negotiation. 'agreement' - all agents reached
	// consensus; 'disagreement' - step budget exhausted without agreement; 'broken' -
	// a participant dropped out or returned an invalid offer; 'error' - pipeline
	// exception during execution.
	Outcome NegotiateCommitSemanticContextOutcome `json:"outcome" yaml:"outcome" mapstructure:"outcome"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion string `json:"schema_version,omitempty,omitzero" yaml:"schema_version,omitempty" mapstructure:"schema_version,omitempty"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id" yaml:"session_id" mapstructure:"session_id"`
}

// List of agent IDs that participated in this negotiation.
type NegotiateCommitSemanticContextAgentsNegotiating []string

type NegotiateCommitSemanticContextAgentsNegotiating_0 []string

type NegotiateCommitSemanticContextContentText_0 *string

type NegotiateCommitSemanticContextEncoding string

const NegotiateCommitSemanticContextEncodingHybrid NegotiateCommitSemanticContextEncoding = "hybrid"
const NegotiateCommitSemanticContextEncodingJson NegotiateCommitSemanticContextEncoding = "json"
const NegotiateCommitSemanticContextEncodingStructuredText NegotiateCommitSemanticContextEncoding = "structured_text"

var enumValues_NegotiateCommitSemanticContextEncoding = []interface{}{
	"json",
	"structured_text",
	"hybrid",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateCommitSemanticContextEncoding) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NegotiateCommitSemanticContextEncoding {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NegotiateCommitSemanticContextEncoding, v)
	}
	*j = NegotiateCommitSemanticContextEncoding(v)
	return nil
}

type NegotiateCommitSemanticContextErrorMessage_0 *string

// Agreed option per issue. Each entry is {'issue_id': str, 'chosen_option': str}.
// None when negotiation ended without agreement.
type NegotiateCommitSemanticContextFinalAgreement []map[string]interface{}

type NegotiateCommitSemanticContextFinalAgreement_0 []map[string]interface{}

type NegotiateCommitSemanticContextOutcome string

const NegotiateCommitSemanticContextOutcomeAgreement NegotiateCommitSemanticContextOutcome = "agreement"
const NegotiateCommitSemanticContextOutcomeBroken NegotiateCommitSemanticContextOutcome = "broken"
const NegotiateCommitSemanticContextOutcomeDisagreement NegotiateCommitSemanticContextOutcome = "disagreement"
const NegotiateCommitSemanticContextOutcomeError NegotiateCommitSemanticContextOutcome = "error"

var enumValues_NegotiateCommitSemanticContextOutcome = []interface{}{
	"agreement",
	"disagreement",
	"broken",
	"error",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateCommitSemanticContextOutcome) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NegotiateCommitSemanticContextOutcome {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NegotiateCommitSemanticContextOutcome, v)
	}
	*j = NegotiateCommitSemanticContextOutcome(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateCommitSemanticContext) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["outcome"]; raw != nil && !ok {
		return fmt.Errorf("field outcome in NegotiateCommitSemanticContext: required")
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in NegotiateCommitSemanticContext: required")
	}
	type Plain NegotiateCommitSemanticContext
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["encoding"]; !ok || v == nil {
		plain.Encoding = "json"
	}
	if v, ok := raw["schema_version"]; !ok || v == nil {
		plain.SchemaVersion = "1.0"
	}
	*j = NegotiateCommitSemanticContext(plain)
	return nil
}

// SAO-specific semantic context for “kind='negotiate'“ messages.
//
// Carries a full NegMAS SAO negotiation snapshot so that receivers have
// complete mechanism state, the latest response, and optionally the NMI
// configuration - all in one well-typed envelope.
type NegotiateSemanticContext struct {
	// Encoding corresponds to the JSON schema field "encoding".
	Encoding NegotiateSemanticContextEncoding `json:"encoding,omitempty,omitzero" yaml:"encoding,omitempty" mapstructure:"encoding,omitempty"`

	// Nmi corresponds to the JSON schema field "nmi".
	Nmi *NegotiateSemanticContextNmi `json:"nmi,omitempty,omitzero" yaml:"nmi,omitempty" mapstructure:"nmi,omitempty"`

	// OfferValidationFailure corresponds to the JSON schema field
	// "offer_validation_failure".
	OfferValidationFailure *NegotiateSemanticContextOfferValidationFailure `json:"offer_validation_failure,omitempty,omitzero" yaml:"offer_validation_failure,omitempty" mapstructure:"offer_validation_failure,omitempty"`

	// SaoResponse corresponds to the JSON schema field "sao_response".
	SaoResponse *NegotiateSemanticContextSaoResponse `json:"sao_response,omitempty,omitzero" yaml:"sao_response,omitempty" mapstructure:"sao_response,omitempty"`

	// SaoState corresponds to the JSON schema field "sao_state".
	SaoState *NegotiateSemanticContextSaoState `json:"sao_state,omitempty,omitzero" yaml:"sao_state,omitempty" mapstructure:"sao_state,omitempty"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion string `json:"schema_version,omitempty,omitzero" yaml:"schema_version,omitempty" mapstructure:"schema_version,omitempty"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID string `json:"session_id" yaml:"session_id" mapstructure:"session_id"`
}

type NegotiateSemanticContextEncoding string

const NegotiateSemanticContextEncodingHybrid NegotiateSemanticContextEncoding = "hybrid"
const NegotiateSemanticContextEncodingJson NegotiateSemanticContextEncoding = "json"
const NegotiateSemanticContextEncodingStructuredText NegotiateSemanticContextEncoding = "structured_text"

var enumValues_NegotiateSemanticContextEncoding = []interface{}{
	"json",
	"structured_text",
	"hybrid",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateSemanticContextEncoding) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_NegotiateSemanticContextEncoding {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_NegotiateSemanticContextEncoding, v)
	}
	*j = NegotiateSemanticContextEncoding(v)
	return nil
}

// NegotiatorMechanismInterface configuration snapshot for SAO.
//
// NegMAS source: negmas.sao.common.SAONMI (frozen attrs, inherits
// NegotiatorMechanismInterface)
//
// Omissions vs. the real SAONMI:
// - “_mechanism“ back-reference (internal, not serialisable)
// - “time_limit“ and “n_steps“ computed fields (derive at runtime)
//
// All NegotiatorMechanismInterface base fields are present with defaults so
// this model can be built from a plain dict / JSON snapshot without needing
// a live mechanism object.
type NegotiateSemanticContextNmi struct {
	// AllowNegotiatorsToLeave corresponds to the JSON schema field
	// "allow_negotiators_to_leave".
	AllowNegotiatorsToLeave bool `json:"allow_negotiators_to_leave,omitempty,omitzero" yaml:"allow_negotiators_to_leave,omitempty" mapstructure:"allow_negotiators_to_leave,omitempty"`

	// AllowNoneWithData corresponds to the JSON schema field "allow_none_with_data".
	AllowNoneWithData bool `json:"allow_none_with_data,omitempty,omitzero" yaml:"allow_none_with_data,omitempty" mapstructure:"allow_none_with_data,omitempty"`

	// Annotation corresponds to the JSON schema field "annotation".
	Annotation SAONMIAnnotation `json:"annotation,omitempty,omitzero" yaml:"annotation,omitempty" mapstructure:"annotation,omitempty"`

	// DynamicEntry corresponds to the JSON schema field "dynamic_entry".
	DynamicEntry bool `json:"dynamic_entry,omitempty,omitzero" yaml:"dynamic_entry,omitempty" mapstructure:"dynamic_entry,omitempty"`

	// EndOnNoResponse corresponds to the JSON schema field "end_on_no_response".
	EndOnNoResponse bool `json:"end_on_no_response,omitempty,omitzero" yaml:"end_on_no_response,omitempty" mapstructure:"end_on_no_response,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id,omitempty,omitzero" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// MaxNNegotiators corresponds to the JSON schema field "max_n_negotiators".
	MaxNNegotiators interface{} `json:"max_n_negotiators,omitempty,omitzero" yaml:"max_n_negotiators,omitempty" mapstructure:"max_n_negotiators,omitempty"`

	// NOutcomes corresponds to the JSON schema field "n_outcomes".
	NOutcomes interface{} `json:"n_outcomes,omitempty,omitzero" yaml:"n_outcomes,omitempty" mapstructure:"n_outcomes,omitempty"`

	// NegotiatorTimeLimit corresponds to the JSON schema field
	// "negotiator_time_limit".
	NegotiatorTimeLimit float64 `json:"negotiator_time_limit,omitempty,omitzero" yaml:"negotiator_time_limit,omitempty" mapstructure:"negotiator_time_limit,omitempty"`

	// OfferingIsAccepting corresponds to the JSON schema field
	// "offering_is_accepting".
	OfferingIsAccepting bool `json:"offering_is_accepting,omitempty,omitzero" yaml:"offering_is_accepting,omitempty" mapstructure:"offering_is_accepting,omitempty"`

	// OneOfferPerStep corresponds to the JSON schema field "one_offer_per_step".
	OneOfferPerStep bool `json:"one_offer_per_step,omitempty,omitzero" yaml:"one_offer_per_step,omitempty" mapstructure:"one_offer_per_step,omitempty"`

	// Pend corresponds to the JSON schema field "pend".
	Pend float64 `json:"pend,omitempty,omitzero" yaml:"pend,omitempty" mapstructure:"pend,omitempty"`

	// PendPerSecond corresponds to the JSON schema field "pend_per_second".
	PendPerSecond float64 `json:"pend_per_second,omitempty,omitzero" yaml:"pend_per_second,omitempty" mapstructure:"pend_per_second,omitempty"`

	// PrivateNSteps corresponds to the JSON schema field "private_n_steps".
	PrivateNSteps interface{} `json:"private_n_steps,omitempty,omitzero" yaml:"private_n_steps,omitempty" mapstructure:"private_n_steps,omitempty"`

	// PrivateTimeLimit corresponds to the JSON schema field "private_time_limit".
	PrivateTimeLimit float64 `json:"private_time_limit,omitempty,omitzero" yaml:"private_time_limit,omitempty" mapstructure:"private_time_limit,omitempty"`

	// SharedNSteps corresponds to the JSON schema field "shared_n_steps".
	SharedNSteps interface{} `json:"shared_n_steps,omitempty,omitzero" yaml:"shared_n_steps,omitempty" mapstructure:"shared_n_steps,omitempty"`

	// SharedTimeLimit corresponds to the JSON schema field "shared_time_limit".
	SharedTimeLimit float64 `json:"shared_time_limit,omitempty,omitzero" yaml:"shared_time_limit,omitempty" mapstructure:"shared_time_limit,omitempty"`

	// StepTimeLimit corresponds to the JSON schema field "step_time_limit".
	StepTimeLimit float64 `json:"step_time_limit,omitempty,omitzero" yaml:"step_time_limit,omitempty" mapstructure:"step_time_limit,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateSemanticContextNmi) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var negotiateSemanticContextNmi_0 NegotiateSemanticContextNmi_0
	var errs []error
	if err := negotiateSemanticContextNmi_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain NegotiateSemanticContextNmi
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NegotiateSemanticContextNmi(plain)
	return nil
}

type NegotiateSemanticContextOfferValidationFailure map[string]interface{}

type NegotiateSemanticContextOfferValidationFailure_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateSemanticContextOfferValidationFailure_0) UnmarshalJSON(value []byte) error {
	type Plain NegotiateSemanticContextOfferValidationFailure_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NegotiateSemanticContextOfferValidationFailure_0(plain)
	return nil
}

// A single negotiator response in one SAO round.
// Encapsulates the decision (accept / reject / end / …) plus an optional offer.
//
// NegMAS source: negmas.sao.common.SAOResponse
type NegotiateSemanticContextSaoResponse struct {
	// Data corresponds to the JSON schema field "data".
	Data *NegotiateSemanticContextSaoResponseData `json:"data,omitempty,omitzero" yaml:"data,omitempty" mapstructure:"data,omitempty"`

	// Outcome corresponds to the JSON schema field "outcome".
	Outcome *NegotiateSemanticContextSaoResponseOutcome `json:"outcome,omitempty,omitzero" yaml:"outcome,omitempty" mapstructure:"outcome,omitempty"`

	// Response corresponds to the JSON schema field "response".
	Response ResponseType `json:"response,omitempty,omitzero" yaml:"response,omitempty" mapstructure:"response,omitempty"`
}

type NegotiateSemanticContextSaoResponseData map[string]interface{}

type NegotiateSemanticContextSaoResponseOutcome map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateSemanticContextSaoResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var negotiateSemanticContextSaoResponse_0 NegotiateSemanticContextSaoResponse_0
	var errs []error
	if err := negotiateSemanticContextSaoResponse_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain NegotiateSemanticContextSaoResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NegotiateSemanticContextSaoResponse(plain)
	return nil
}

// Full mechanism state for the Stacked Alternating Offers (SAO) protocol.
//
// NegMAS source: negmas.sao.common.SAOState
// Fields are declared in addition to those inherited from GBState /
// MechanismState.
type NegotiateSemanticContextSaoState struct {
	// Agreement corresponds to the JSON schema field "agreement".
	Agreement *NegotiateSemanticContextSaoStateAgreement `json:"agreement,omitempty,omitzero" yaml:"agreement,omitempty" mapstructure:"agreement,omitempty"`

	// Broken corresponds to the JSON schema field "broken".
	Broken bool `json:"broken,omitempty,omitzero" yaml:"broken,omitempty" mapstructure:"broken,omitempty"`

	// CurrentData corresponds to the JSON schema field "current_data".
	CurrentData *NegotiateSemanticContextSaoStateCurrentData `json:"current_data,omitempty,omitzero" yaml:"current_data,omitempty" mapstructure:"current_data,omitempty"`

	// CurrentOffer corresponds to the JSON schema field "current_offer".
	CurrentOffer *NegotiateSemanticContextSaoStateCurrentOffer `json:"current_offer,omitempty,omitzero" yaml:"current_offer,omitempty" mapstructure:"current_offer,omitempty"`

	// CurrentProposer corresponds to the JSON schema field "current_proposer".
	CurrentProposer interface{} `json:"current_proposer,omitempty,omitzero" yaml:"current_proposer,omitempty" mapstructure:"current_proposer,omitempty"`

	// CurrentProposerAgent corresponds to the JSON schema field
	// "current_proposer_agent".
	CurrentProposerAgent interface{} `json:"current_proposer_agent,omitempty,omitzero" yaml:"current_proposer_agent,omitempty" mapstructure:"current_proposer_agent,omitempty"`

	// ErredAgent corresponds to the JSON schema field "erred_agent".
	ErredAgent string `json:"erred_agent,omitempty,omitzero" yaml:"erred_agent,omitempty" mapstructure:"erred_agent,omitempty"`

	// ErredNegotiator corresponds to the JSON schema field "erred_negotiator".
	ErredNegotiator string `json:"erred_negotiator,omitempty,omitzero" yaml:"erred_negotiator,omitempty" mapstructure:"erred_negotiator,omitempty"`

	// ErrorDetails corresponds to the JSON schema field "error_details".
	ErrorDetails string `json:"error_details,omitempty,omitzero" yaml:"error_details,omitempty" mapstructure:"error_details,omitempty"`

	// HasError corresponds to the JSON schema field "has_error".
	HasError bool `json:"has_error,omitempty,omitzero" yaml:"has_error,omitempty" mapstructure:"has_error,omitempty"`

	// LastNegotiator corresponds to the JSON schema field "last_negotiator".
	LastNegotiator interface{} `json:"last_negotiator,omitempty,omitzero" yaml:"last_negotiator,omitempty" mapstructure:"last_negotiator,omitempty"`

	// LastThread corresponds to the JSON schema field "last_thread".
	LastThread string `json:"last_thread,omitempty,omitzero" yaml:"last_thread,omitempty" mapstructure:"last_thread,omitempty"`

	// LeftNegotiators corresponds to the JSON schema field "left_negotiators".
	LeftNegotiators []string `json:"left_negotiators,omitempty,omitzero" yaml:"left_negotiators,omitempty" mapstructure:"left_negotiators,omitempty"`

	// NAcceptances corresponds to the JSON schema field "n_acceptances".
	NAcceptances int `json:"n_acceptances,omitempty,omitzero" yaml:"n_acceptances,omitempty" mapstructure:"n_acceptances,omitempty"`

	// NNegotiators corresponds to the JSON schema field "n_negotiators".
	NNegotiators int `json:"n_negotiators,omitempty,omitzero" yaml:"n_negotiators,omitempty" mapstructure:"n_negotiators,omitempty"`

	// NewData corresponds to the JSON schema field "new_data".
	NewData [][]interface{} `json:"new_data,omitempty,omitzero" yaml:"new_data,omitempty" mapstructure:"new_data,omitempty"`

	// NewOffererAgents corresponds to the JSON schema field "new_offerer_agents".
	NewOffererAgents []interface{} `json:"new_offerer_agents,omitempty,omitzero" yaml:"new_offerer_agents,omitempty" mapstructure:"new_offerer_agents,omitempty"`

	// NewOffers corresponds to the JSON schema field "new_offers".
	NewOffers [][]interface{} `json:"new_offers,omitempty,omitzero" yaml:"new_offers,omitempty" mapstructure:"new_offers,omitempty"`

	// RelativeTime corresponds to the JSON schema field "relative_time".
	RelativeTime float64 `json:"relative_time,omitempty,omitzero" yaml:"relative_time,omitempty" mapstructure:"relative_time,omitempty"`

	// Results corresponds to the JSON schema field "results".
	Results interface{} `json:"results,omitempty,omitzero" yaml:"results,omitempty" mapstructure:"results,omitempty"`

	// Running corresponds to the JSON schema field "running".
	Running bool `json:"running,omitempty,omitzero" yaml:"running,omitempty" mapstructure:"running,omitempty"`

	// Started corresponds to the JSON schema field "started".
	Started bool `json:"started,omitempty,omitzero" yaml:"started,omitempty" mapstructure:"started,omitempty"`

	// Step corresponds to the JSON schema field "step".
	Step int `json:"step,omitempty,omitzero" yaml:"step,omitempty" mapstructure:"step,omitempty"`

	// Threads corresponds to the JSON schema field "threads".
	Threads SAOStateThreads `json:"threads,omitempty,omitzero" yaml:"threads,omitempty" mapstructure:"threads,omitempty"`

	// Time corresponds to the JSON schema field "time".
	Time float64 `json:"time,omitempty,omitzero" yaml:"time,omitempty" mapstructure:"time,omitempty"`

	// Timedout corresponds to the JSON schema field "timedout".
	Timedout bool `json:"timedout,omitempty,omitzero" yaml:"timedout,omitempty" mapstructure:"timedout,omitempty"`

	// Waiting corresponds to the JSON schema field "waiting".
	Waiting bool `json:"waiting,omitempty,omitzero" yaml:"waiting,omitempty" mapstructure:"waiting,omitempty"`
}

type NegotiateSemanticContextSaoStateAgreement map[string]interface{}

type NegotiateSemanticContextSaoStateCurrentData map[string]interface{}

type NegotiateSemanticContextSaoStateCurrentOffer map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateSemanticContextSaoState) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var negotiateSemanticContextSaoState_0 NegotiateSemanticContextSaoState_0
	var errs []error
	if err := negotiateSemanticContextSaoState_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain NegotiateSemanticContextSaoState
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = NegotiateSemanticContextSaoState(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NegotiateSemanticContext) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["session_id"]; raw != nil && !ok {
		return fmt.Errorf("field session_id in NegotiateSemanticContext: required")
	}
	type Plain NegotiateSemanticContext
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["encoding"]; !ok || v == nil {
		plain.Encoding = "json"
	}
	if v, ok := raw["schema_version"]; !ok || v == nil {
		plain.SchemaVersion = "1.0"
	}
	*j = NegotiateSemanticContext(plain)
	return nil
}

// Data governance and access-control labels applied to the message.
// ## TODO Nandu, Peter please review
type PolicyLabel struct {
	// Propagation corresponds to the JSON schema field "propagation".
	Propagation string `json:"propagation" yaml:"propagation" mapstructure:"propagation"`

	// RetentionPolicy corresponds to the JSON schema field "retention_policy".
	RetentionPolicy string `json:"retention_policy" yaml:"retention_policy" mapstructure:"retention_policy"`

	// Sensitivity corresponds to the JSON schema field "sensitivity".
	Sensitivity string `json:"sensitivity" yaml:"sensitivity" mapstructure:"sensitivity"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PolicyLabel) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["propagation"]; raw != nil && !ok {
		return fmt.Errorf("field propagation in PolicyLabel: required")
	}
	if _, ok := raw["retention_policy"]; raw != nil && !ok {
		return fmt.Errorf("field retention_policy in PolicyLabel: required")
	}
	if _, ok := raw["sensitivity"]; raw != nil && !ok {
		return fmt.Errorf("field sensitivity in PolicyLabel: required")
	}
	type Plain PolicyLabel
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PolicyLabel(plain)
	return nil
}

// Tracks the origin and lineage of a message - who created it, from what source,
// and through which transformations. Fields TBD.
type Provenance map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Provenance) UnmarshalJSON(value []byte) error {
	type Plain Provenance
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Provenance(plain)
	return nil
}

type ResponseType int

var enumValues_ResponseType = []interface{}{
	0,
	1,
	2,
	3,
	4,
	5,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResponseType) UnmarshalJSON(value []byte) error {
	var v int
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ResponseType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ResponseType, v)
	}
	*j = ResponseType(v)
	return nil
}

// Actors block for SAB messages. groups is always null (no MAS/workspace IDs).
type SABActors struct {
	// Actors corresponds to the JSON schema field "actors".
	Actors []Actor `json:"actors" yaml:"actors" mapstructure:"actors"`

	// Groups corresponds to the JSON schema field "groups".
	Groups *SABActorsGroups `json:"groups,omitempty,omitzero" yaml:"groups,omitempty" mapstructure:"groups,omitempty"`
}

type SABActorsGroups map[string]interface{}

type SABActorsGroups_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABActorsGroups_0) UnmarshalJSON(value []byte) error {
	type Plain SABActorsGroups_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SABActorsGroups_0(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABActors) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["actors"]; raw != nil && !ok {
		return fmt.Errorf("field actors in SABActors: required")
	}
	type Plain SABActors
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SABActors(plain)
	return nil
}

// header.attributes block written by the SAB adapter.
type SABAttributes struct {
	// dt_created from the wrapped SSTP message (ISO 8601).
	MsgCreatedAt string `json:"msg_created_at" yaml:"msg_created_at" mapstructure:"msg_created_at"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABAttributes) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["msg_created_at"]; raw != nil && !ok {
		return fmt.Errorf("field msg_created_at in SABAttributes: required")
	}
	type Plain SABAttributes
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SABAttributes(plain)
	return nil
}

// payload.data when the wrapped SSTP message is kind=commit.
type SABCommitPayloadData struct {
	// ISO 8601 creation timestamp.
	DtCreated string `json:"dt_created" yaml:"dt_created" mapstructure:"dt_created"`

	// MessageID corresponds to the JSON schema field "message_id".
	MessageID string `json:"message_id" yaml:"message_id" mapstructure:"message_id"`

	// Origin corresponds to the JSON schema field "origin".
	Origin SABOrigin `json:"origin" yaml:"origin" mapstructure:"origin"`

	// SHA-256 hex digest of the original payload.
	PayloadHash string `json:"payload_hash" yaml:"payload_hash" mapstructure:"payload_hash"`

	// SemanticContext corresponds to the JSON schema field "semantic_context".
	SemanticContext NegotiateCommitSemanticContext `json:"semantic_context" yaml:"semantic_context" mapstructure:"semantic_context"`

	// SSTP protocol version.
	Version string `json:"version,omitempty,omitzero" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABCommitPayloadData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dt_created"]; raw != nil && !ok {
		return fmt.Errorf("field dt_created in SABCommitPayloadData: required")
	}
	if _, ok := raw["message_id"]; raw != nil && !ok {
		return fmt.Errorf("field message_id in SABCommitPayloadData: required")
	}
	if _, ok := raw["origin"]; raw != nil && !ok {
		return fmt.Errorf("field origin in SABCommitPayloadData: required")
	}
	if _, ok := raw["payload_hash"]; raw != nil && !ok {
		return fmt.Errorf("field payload_hash in SABCommitPayloadData: required")
	}
	if _, ok := raw["semantic_context"]; raw != nil && !ok {
		return fmt.Errorf("field semantic_context in SABCommitPayloadData: required")
	}
	type Plain SABCommitPayloadData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["version"]; !ok || v == nil {
		plain.Version = "0"
	}
	*j = SABCommitPayloadData(plain)
	return nil
}

// L9 header constrained to the SAB subprotocol.
type SABHeader struct {
	// Actors corresponds to the JSON schema field "actors".
	Actors SABActors `json:"actors" yaml:"actors" mapstructure:"actors"`

	// Attributes corresponds to the JSON schema field "attributes".
	Attributes *SABHeaderAttributes `json:"attributes,omitempty,omitzero" yaml:"attributes,omitempty" mapstructure:"attributes,omitempty"`

	// Present when a topic, issues, or options_per_issue are available. context.topic
	// encodes: '<mission> | issues: [...] | options_per_issue: {...}'.
	// context.semantic.schema_id = 'urn:ioc:schema:sab-l9:v1' identifies this
	// envelope.
	Context *SABHeaderContext `json:"context,omitempty,omitzero" yaml:"context,omitempty" mapstructure:"context,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind SABHeaderKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Message corresponds to the JSON schema field "message".
	Message *SABHeaderMessage `json:"message,omitempty,omitzero" yaml:"message,omitempty" mapstructure:"message,omitempty"`

	// Policy corresponds to the JSON schema field "policy".
	Policy *SABHeaderPolicy `json:"policy,omitempty,omitzero" yaml:"policy,omitempty" mapstructure:"policy,omitempty"`

	// Protocol corresponds to the JSON schema field "protocol".
	Protocol string `json:"protocol" yaml:"protocol" mapstructure:"protocol"`

	// Subkind corresponds to the JSON schema field "subkind".
	Subkind SABHeaderSubkind `json:"subkind" yaml:"subkind" mapstructure:"subkind"`

	// Subprotocol corresponds to the JSON schema field "subprotocol".
	Subprotocol string `json:"subprotocol" yaml:"subprotocol" mapstructure:"subprotocol"`

	// SSTP version string copied from the wrapped message.
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

// header.attributes block written by the SAB adapter.
type SABHeaderAttributes struct {
	// dt_created from the wrapped SSTP message (ISO 8601).
	MsgCreatedAt string `json:"msg_created_at" yaml:"msg_created_at" mapstructure:"msg_created_at"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABHeaderAttributes) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var sABHeaderAttributes_0 SABHeaderAttributes_0
	var errs []error
	if err := sABHeaderAttributes_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain SABHeaderAttributes
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SABHeaderAttributes(plain)
	return nil
}

// Present when a topic, issues, or options_per_issue are available. context.topic
// encodes: '<mission> | issues: [...] | options_per_issue: {...}'.
// context.semantic.schema_id = 'urn:ioc:schema:sab-l9:v1' identifies this
// envelope.
type SABHeaderContext struct {
	// Epistemic corresponds to the JSON schema field "epistemic".
	Epistemic *SABHeaderContextEpistemic `json:"epistemic,omitempty,omitzero" yaml:"epistemic,omitempty" mapstructure:"epistemic,omitempty"`

	// Semantic corresponds to the JSON schema field "semantic".
	Semantic *SABHeaderContextSemantic `json:"semantic,omitempty,omitzero" yaml:"semantic,omitempty" mapstructure:"semantic,omitempty"`

	// Topic corresponds to the JSON schema field "topic".
	Topic string `json:"topic" yaml:"topic" mapstructure:"topic"`
}

// Agent epistemic (belief/knowledge) state at the time the message was sent.
// Currently a placeholder - fields will be added as the model is defined.
type SABHeaderContextEpistemic map[string]interface{}

// Describes the semantic/ontological framework needed to correctly interpret the
// payload.
// The CFN routing layer uses this to select appropriate cognitive engines (CEs).
type SABHeaderContextSemantic struct {
	// OntologyRef corresponds to the JSON schema field "ontology_ref".
	OntologyRef string `json:"ontology_ref" yaml:"ontology_ref" mapstructure:"ontology_ref"`

	// Provenance corresponds to the JSON schema field "provenance".
	Provenance *SABHeaderContextSemanticProvenance `json:"provenance,omitempty,omitzero" yaml:"provenance,omitempty" mapstructure:"provenance,omitempty"`

	// SchemaID corresponds to the JSON schema field "schema_id".
	SchemaID string `json:"schema_id" yaml:"schema_id" mapstructure:"schema_id"`
}

// Tracks the origin and lineage of a message - who created it, from what source,
// and through which transformations. Fields TBD.
type SABHeaderContextSemanticProvenance map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABHeaderContextSemantic) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var sABHeaderContextSemantic_0 SABHeaderContextSemantic_0
	var errs []error
	if err := sABHeaderContextSemantic_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain SABHeaderContextSemantic
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SABHeaderContextSemantic(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABHeaderContext) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var sABHeaderContext_0 SABHeaderContext_0
	var errs []error
	if err := sABHeaderContext_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain SABHeaderContext
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SABHeaderContext(plain)
	return nil
}

type SABHeaderKind string

const SABHeaderKindCommit SABHeaderKind = "commit"
const SABHeaderKindContingency SABHeaderKind = "contingency"

var enumValues_SABHeaderKind = []interface{}{
	"contingency",
	"commit",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABHeaderKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SABHeaderKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SABHeaderKind, v)
	}
	*j = SABHeaderKind(v)
	return nil
}

// Represents a message in the protocol.
type SABHeaderMessage struct {
	// Episode corresponds to the JSON schema field "episode".
	Episode string `json:"episode" yaml:"episode" mapstructure:"episode"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id" yaml:"id" mapstructure:"id"`

	// Parents corresponds to the JSON schema field "parents".
	// Ordered list of parent message IDs. Empty list for root messages.
	Parents []string `json:"parents" yaml:"parents" mapstructure:"parents"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABHeaderMessage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var sABHeaderMessage_0 SABHeaderMessage_0
	var errs []error
	if err := sABHeaderMessage_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain SABHeaderMessage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SABHeaderMessage(plain)
	return nil
}

// Data governance and access-control labels applied to the message.
// ## TODO Nandu, Peter please review
type SABHeaderPolicy struct {
	// Propagation corresponds to the JSON schema field "propagation".
	Propagation string `json:"propagation" yaml:"propagation" mapstructure:"propagation"`

	// RetentionPolicy corresponds to the JSON schema field "retention_policy".
	RetentionPolicy string `json:"retention_policy" yaml:"retention_policy" mapstructure:"retention_policy"`

	// Sensitivity corresponds to the JSON schema field "sensitivity".
	Sensitivity string `json:"sensitivity" yaml:"sensitivity" mapstructure:"sensitivity"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABHeaderPolicy) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var sABHeaderPolicy_0 SABHeaderPolicy_0
	var errs []error
	if err := sABHeaderPolicy_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain SABHeaderPolicy
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SABHeaderPolicy(plain)
	return nil
}

type SABHeaderSubkind string

const SABHeaderSubkindConverged SABHeaderSubkind = "converged"
const SABHeaderSubkindDisagreement SABHeaderSubkind = "disagreement"
const SABHeaderSubkindNegotiate SABHeaderSubkind = "negotiate"
const SABHeaderSubkindTimeout SABHeaderSubkind = "timeout"

var enumValues_SABHeaderSubkind = []interface{}{
	"negotiate",
	"converged",
	"disagreement",
	"timeout",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABHeaderSubkind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SABHeaderSubkind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SABHeaderSubkind, v)
	}
	*j = SABHeaderSubkind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABHeader) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["actors"]; raw != nil && !ok {
		return fmt.Errorf("field actors in SABHeader: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in SABHeader: required")
	}
	if _, ok := raw["protocol"]; raw != nil && !ok {
		return fmt.Errorf("field protocol in SABHeader: required")
	}
	if _, ok := raw["subkind"]; raw != nil && !ok {
		return fmt.Errorf("field subkind in SABHeader: required")
	}
	if _, ok := raw["subprotocol"]; raw != nil && !ok {
		return fmt.Errorf("field subprotocol in SABHeader: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in SABHeader: required")
	}
	type Plain SABHeader
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Protocol != "SSTP" {
		return fmt.Errorf("field %s: must be equal to %s", "protocol", "SSTP")
	}
	if plain.Subprotocol != "SAB" {
		return fmt.Errorf("field %s: must be equal to %s", "subprotocol", "SAB")
	}
	*j = SABHeader(plain)
	return nil
}

// payload.data when the wrapped SSTP message is kind=intent.
type SABIntentPayloadData struct {
	// ISO 8601 creation timestamp.
	DtCreated string `json:"dt_created" yaml:"dt_created" mapstructure:"dt_created"`

	// MessageID corresponds to the JSON schema field "message_id".
	MessageID string `json:"message_id" yaml:"message_id" mapstructure:"message_id"`

	// Origin corresponds to the JSON schema field "origin".
	Origin SABOrigin `json:"origin" yaml:"origin" mapstructure:"origin"`

	// SHA-256 hex digest of the original payload.
	PayloadHash string `json:"payload_hash" yaml:"payload_hash" mapstructure:"payload_hash"`

	// SemanticContext corresponds to the JSON schema field "semantic_context".
	SemanticContext SemanticContext `json:"semantic_context" yaml:"semantic_context" mapstructure:"semantic_context"`

	// SSTP protocol version.
	Version string `json:"version,omitempty,omitzero" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABIntentPayloadData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dt_created"]; raw != nil && !ok {
		return fmt.Errorf("field dt_created in SABIntentPayloadData: required")
	}
	if _, ok := raw["message_id"]; raw != nil && !ok {
		return fmt.Errorf("field message_id in SABIntentPayloadData: required")
	}
	if _, ok := raw["origin"]; raw != nil && !ok {
		return fmt.Errorf("field origin in SABIntentPayloadData: required")
	}
	if _, ok := raw["payload_hash"]; raw != nil && !ok {
		return fmt.Errorf("field payload_hash in SABIntentPayloadData: required")
	}
	if _, ok := raw["semantic_context"]; raw != nil && !ok {
		return fmt.Errorf("field semantic_context in SABIntentPayloadData: required")
	}
	type Plain SABIntentPayloadData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["version"]; !ok || v == nil {
		plain.Version = "0"
	}
	*j = SABIntentPayloadData(plain)
	return nil
}

// An L9 envelope carrying an SSTP message over the SAB subprotocol.
//
// SAB (Semantic Alignment via Bargaining) is a subprotocol of SSTP that
// enables agents to reach semantic alignment through a bargaining process
// implemented with NegMAS Stacked Alternating Offers (SAO).
//
// Kind / subkind mapping
// ----------------------
// SSTP kind            L9 kind       L9 subkind
// ─────────────────    ──────────    ──────────
// intent               contingency   negotiate
// negotiate            contingency   negotiate
// commit / agreement   commit        converged
// commit / disagree    commit        disagreement
// commit / broken|err  commit        timeout
type SABL9Json struct {
	// Header corresponds to the JSON schema field "header".
	Header SABHeader `json:"header" yaml:"header" mapstructure:"header"`

	// Payload corresponds to the JSON schema field "payload".
	Payload SABL9Payload `json:"payload" yaml:"payload" mapstructure:"payload"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABL9Json) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["header"]; raw != nil && !ok {
		return fmt.Errorf("field header in SABL9Json: required")
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in SABL9Json: required")
	}
	type Plain SABL9Json
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SABL9Json(plain)
	return nil
}

// L9 payload constrained to SAB wire format.
type SABL9Payload struct {
	// The stripped SSTP message body. Discriminate by semantic_context.schema_id:
	// 'urn:ioc:schema:intent:v1' → intent, 'urn:ioc:schema:negotiate:negmas-sao:v1' →
	// negotiate, 'urn:ioc:schema:negotiate:commit:v1' → commit.
	Data SABL9PayloadData `json:"data" yaml:"data" mapstructure:"data"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// The stripped SSTP message body. Discriminate by semantic_context.schema_id:
// 'urn:ioc:schema:intent:v1' → intent, 'urn:ioc:schema:negotiate:negmas-sao:v1' →
// negotiate, 'urn:ioc:schema:negotiate:commit:v1' → commit.
type SABL9PayloadData struct {
	// ISO 8601 creation timestamp.
	DtCreated string `json:"dt_created" yaml:"dt_created" mapstructure:"dt_created"`

	// MessageID corresponds to the JSON schema field "message_id".
	MessageID string `json:"message_id" yaml:"message_id" mapstructure:"message_id"`

	// Origin corresponds to the JSON schema field "origin".
	Origin SABOrigin `json:"origin" yaml:"origin" mapstructure:"origin"`

	// SHA-256 hex digest of the original payload.
	PayloadHash string `json:"payload_hash" yaml:"payload_hash" mapstructure:"payload_hash"`

	// SemanticContext corresponds to the JSON schema field "semantic_context".
	SemanticContext SemanticContext `json:"semantic_context" yaml:"semantic_context" mapstructure:"semantic_context"`

	// SSTP protocol version.
	Version string `json:"version,omitempty,omitzero" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABL9PayloadData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var sABL9PayloadData_0 SABL9PayloadData_0
	var sABL9PayloadData_1 SABL9PayloadData_1
	var sABL9PayloadData_2 SABL9PayloadData_2
	var errs []error
	if err := sABL9PayloadData_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := sABL9PayloadData_1.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := sABL9PayloadData_2.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 3 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain SABL9PayloadData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SABL9PayloadData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABL9Payload) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in SABL9Payload: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in SABL9Payload: required")
	}
	type Plain SABL9Payload
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Type != "json-schema" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "json-schema")
	}
	*j = SABL9Payload(plain)
	return nil
}

// payload.data when the wrapped SSTP message is kind=negotiate.
type SABNegotiatePayloadData struct {
	// ISO 8601 creation timestamp.
	DtCreated string `json:"dt_created" yaml:"dt_created" mapstructure:"dt_created"`

	// MessageID corresponds to the JSON schema field "message_id".
	MessageID string `json:"message_id" yaml:"message_id" mapstructure:"message_id"`

	// Origin corresponds to the JSON schema field "origin".
	Origin SABOrigin `json:"origin" yaml:"origin" mapstructure:"origin"`

	// SHA-256 hex digest of the original payload.
	PayloadHash string `json:"payload_hash" yaml:"payload_hash" mapstructure:"payload_hash"`

	// SemanticContext corresponds to the JSON schema field "semantic_context".
	SemanticContext NegotiateSemanticContext `json:"semantic_context" yaml:"semantic_context" mapstructure:"semantic_context"`

	// SSTP protocol version.
	Version string `json:"version,omitempty,omitzero" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABNegotiatePayloadData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dt_created"]; raw != nil && !ok {
		return fmt.Errorf("field dt_created in SABNegotiatePayloadData: required")
	}
	if _, ok := raw["message_id"]; raw != nil && !ok {
		return fmt.Errorf("field message_id in SABNegotiatePayloadData: required")
	}
	if _, ok := raw["origin"]; raw != nil && !ok {
		return fmt.Errorf("field origin in SABNegotiatePayloadData: required")
	}
	if _, ok := raw["payload_hash"]; raw != nil && !ok {
		return fmt.Errorf("field payload_hash in SABNegotiatePayloadData: required")
	}
	if _, ok := raw["semantic_context"]; raw != nil && !ok {
		return fmt.Errorf("field semantic_context in SABNegotiatePayloadData: required")
	}
	type Plain SABNegotiatePayloadData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["version"]; !ok || v == nil {
		plain.Version = "0"
	}
	*j = SABNegotiatePayloadData(plain)
	return nil
}

// Origin block after tenant_id is stripped by the L9 adapter.
type SABOrigin struct {
	// ActorID corresponds to the JSON schema field "actor_id".
	ActorID string `json:"actor_id" yaml:"actor_id" mapstructure:"actor_id"`

	// Attestation corresponds to the JSON schema field "attestation".
	Attestation interface{} `json:"attestation,omitempty,omitzero" yaml:"attestation,omitempty" mapstructure:"attestation,omitempty"`
}

type SABOriginAttestation_0 *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *SABOrigin) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["actor_id"]; raw != nil && !ok {
		return fmt.Errorf("field actor_id in SABOrigin: required")
	}
	type Plain SABOrigin
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SABOrigin(plain)
	return nil
}

// NegotiatorMechanismInterface configuration snapshot for SAO.
//
// NegMAS source: negmas.sao.common.SAONMI (frozen attrs, inherits
// NegotiatorMechanismInterface)
//
// Omissions vs. the real SAONMI:
// - “_mechanism“ back-reference (internal, not serialisable)
// - “time_limit“ and “n_steps“ computed fields (derive at runtime)
//
// All NegotiatorMechanismInterface base fields are present with defaults so
// this model can be built from a plain dict / JSON snapshot without needing
// a live mechanism object.
type SAONMI struct {
	// AllowNegotiatorsToLeave corresponds to the JSON schema field
	// "allow_negotiators_to_leave".
	AllowNegotiatorsToLeave bool `json:"allow_negotiators_to_leave,omitempty,omitzero" yaml:"allow_negotiators_to_leave,omitempty" mapstructure:"allow_negotiators_to_leave,omitempty"`

	// AllowNoneWithData corresponds to the JSON schema field "allow_none_with_data".
	AllowNoneWithData bool `json:"allow_none_with_data,omitempty,omitzero" yaml:"allow_none_with_data,omitempty" mapstructure:"allow_none_with_data,omitempty"`

	// Annotation corresponds to the JSON schema field "annotation".
	Annotation SAONMIAnnotation `json:"annotation,omitempty,omitzero" yaml:"annotation,omitempty" mapstructure:"annotation,omitempty"`

	// DynamicEntry corresponds to the JSON schema field "dynamic_entry".
	DynamicEntry bool `json:"dynamic_entry,omitempty,omitzero" yaml:"dynamic_entry,omitempty" mapstructure:"dynamic_entry,omitempty"`

	// EndOnNoResponse corresponds to the JSON schema field "end_on_no_response".
	EndOnNoResponse bool `json:"end_on_no_response,omitempty,omitzero" yaml:"end_on_no_response,omitempty" mapstructure:"end_on_no_response,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id,omitempty,omitzero" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// MaxNNegotiators corresponds to the JSON schema field "max_n_negotiators".
	MaxNNegotiators interface{} `json:"max_n_negotiators,omitempty,omitzero" yaml:"max_n_negotiators,omitempty" mapstructure:"max_n_negotiators,omitempty"`

	// NOutcomes corresponds to the JSON schema field "n_outcomes".
	NOutcomes interface{} `json:"n_outcomes,omitempty,omitzero" yaml:"n_outcomes,omitempty" mapstructure:"n_outcomes,omitempty"`

	// NegotiatorTimeLimit corresponds to the JSON schema field
	// "negotiator_time_limit".
	NegotiatorTimeLimit float64 `json:"negotiator_time_limit,omitempty,omitzero" yaml:"negotiator_time_limit,omitempty" mapstructure:"negotiator_time_limit,omitempty"`

	// OfferingIsAccepting corresponds to the JSON schema field
	// "offering_is_accepting".
	OfferingIsAccepting bool `json:"offering_is_accepting,omitempty,omitzero" yaml:"offering_is_accepting,omitempty" mapstructure:"offering_is_accepting,omitempty"`

	// OneOfferPerStep corresponds to the JSON schema field "one_offer_per_step".
	OneOfferPerStep bool `json:"one_offer_per_step,omitempty,omitzero" yaml:"one_offer_per_step,omitempty" mapstructure:"one_offer_per_step,omitempty"`

	// Pend corresponds to the JSON schema field "pend".
	Pend float64 `json:"pend,omitempty,omitzero" yaml:"pend,omitempty" mapstructure:"pend,omitempty"`

	// PendPerSecond corresponds to the JSON schema field "pend_per_second".
	PendPerSecond float64 `json:"pend_per_second,omitempty,omitzero" yaml:"pend_per_second,omitempty" mapstructure:"pend_per_second,omitempty"`

	// PrivateNSteps corresponds to the JSON schema field "private_n_steps".
	PrivateNSteps interface{} `json:"private_n_steps,omitempty,omitzero" yaml:"private_n_steps,omitempty" mapstructure:"private_n_steps,omitempty"`

	// PrivateTimeLimit corresponds to the JSON schema field "private_time_limit".
	PrivateTimeLimit float64 `json:"private_time_limit,omitempty,omitzero" yaml:"private_time_limit,omitempty" mapstructure:"private_time_limit,omitempty"`

	// SharedNSteps corresponds to the JSON schema field "shared_n_steps".
	SharedNSteps interface{} `json:"shared_n_steps,omitempty,omitzero" yaml:"shared_n_steps,omitempty" mapstructure:"shared_n_steps,omitempty"`

	// SharedTimeLimit corresponds to the JSON schema field "shared_time_limit".
	SharedTimeLimit float64 `json:"shared_time_limit,omitempty,omitzero" yaml:"shared_time_limit,omitempty" mapstructure:"shared_time_limit,omitempty"`

	// StepTimeLimit corresponds to the JSON schema field "step_time_limit".
	StepTimeLimit float64 `json:"step_time_limit,omitempty,omitzero" yaml:"step_time_limit,omitempty" mapstructure:"step_time_limit,omitempty"`
}

type SAONMIAnnotation map[string]interface{}

type SAONMIMaxNNegotiators_0 *int

type SAONMIPrivateNSteps_0 *int

type SAONMISharedNSteps_0 *int

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAONMI) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain SAONMI
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allow_negotiators_to_leave"]; !ok || v == nil {
		plain.AllowNegotiatorsToLeave = true
	}
	if v, ok := raw["allow_none_with_data"]; !ok || v == nil {
		plain.AllowNoneWithData = true
	}
	if v, ok := raw["dynamic_entry"]; !ok || v == nil {
		plain.DynamicEntry = false
	}
	if v, ok := raw["end_on_no_response"]; !ok || v == nil {
		plain.EndOnNoResponse = true
	}
	if v, ok := raw["id"]; !ok || v == nil {
		plain.ID = ""
	}
	if v, ok := raw["n_outcomes"]; !ok || v == nil {
		plain.NOutcomes = 0.0
	}
	if v, ok := raw["negotiator_time_limit"]; !ok || v == nil {
		plain.NegotiatorTimeLimit = 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0
	}
	if v, ok := raw["offering_is_accepting"]; !ok || v == nil {
		plain.OfferingIsAccepting = true
	}
	if v, ok := raw["one_offer_per_step"]; !ok || v == nil {
		plain.OneOfferPerStep = false
	}
	if v, ok := raw["pend"]; !ok || v == nil {
		plain.Pend = 0.0
	}
	if v, ok := raw["pend_per_second"]; !ok || v == nil {
		plain.PendPerSecond = 0.0
	}
	if v, ok := raw["private_time_limit"]; !ok || v == nil {
		plain.PrivateTimeLimit = 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0
	}
	if v, ok := raw["shared_time_limit"]; !ok || v == nil {
		plain.SharedTimeLimit = 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0
	}
	if v, ok := raw["step_time_limit"]; !ok || v == nil {
		plain.StepTimeLimit = 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0
	}
	*j = SAONMI(plain)
	return nil
}

// A single negotiator response in one SAO round.
// Encapsulates the decision (accept / reject / end / …) plus an optional offer.
//
// NegMAS source: negmas.sao.common.SAOResponse
type SAOResponse struct {
	// Data corresponds to the JSON schema field "data".
	Data *SAOResponseData `json:"data,omitempty,omitzero" yaml:"data,omitempty" mapstructure:"data,omitempty"`

	// Outcome corresponds to the JSON schema field "outcome".
	Outcome *SAOResponseOutcome `json:"outcome,omitempty,omitzero" yaml:"outcome,omitempty" mapstructure:"outcome,omitempty"`

	// Response corresponds to the JSON schema field "response".
	Response ResponseType `json:"response,omitempty,omitzero" yaml:"response,omitempty" mapstructure:"response,omitempty"`
}

type SAOResponseData map[string]interface{}

type SAOResponseData_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOResponseData_0) UnmarshalJSON(value []byte) error {
	type Plain SAOResponseData_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SAOResponseData_0(plain)
	return nil
}

type SAOResponseOutcome map[string]interface{}

type SAOResponseOutcome_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOResponseOutcome_0) UnmarshalJSON(value []byte) error {
	type Plain SAOResponseOutcome_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SAOResponseOutcome_0(plain)
	return nil
}

type SAOResponseOutcome_1 []interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain SAOResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["response"]; !ok || v == nil {
		plain.Response = 3
	}
	*j = SAOResponse(plain)
	return nil
}

// Full mechanism state for the Stacked Alternating Offers (SAO) protocol.
//
// NegMAS source: negmas.sao.common.SAOState
// Fields are declared in addition to those inherited from GBState /
// MechanismState.
type SAOState struct {
	// Agreement corresponds to the JSON schema field "agreement".
	Agreement *SAOStateAgreement `json:"agreement,omitempty,omitzero" yaml:"agreement,omitempty" mapstructure:"agreement,omitempty"`

	// Broken corresponds to the JSON schema field "broken".
	Broken bool `json:"broken,omitempty,omitzero" yaml:"broken,omitempty" mapstructure:"broken,omitempty"`

	// CurrentData corresponds to the JSON schema field "current_data".
	CurrentData *SAOStateCurrentData `json:"current_data,omitempty,omitzero" yaml:"current_data,omitempty" mapstructure:"current_data,omitempty"`

	// CurrentOffer corresponds to the JSON schema field "current_offer".
	CurrentOffer *SAOStateCurrentOffer `json:"current_offer,omitempty,omitzero" yaml:"current_offer,omitempty" mapstructure:"current_offer,omitempty"`

	// CurrentProposer corresponds to the JSON schema field "current_proposer".
	CurrentProposer interface{} `json:"current_proposer,omitempty,omitzero" yaml:"current_proposer,omitempty" mapstructure:"current_proposer,omitempty"`

	// CurrentProposerAgent corresponds to the JSON schema field
	// "current_proposer_agent".
	CurrentProposerAgent interface{} `json:"current_proposer_agent,omitempty,omitzero" yaml:"current_proposer_agent,omitempty" mapstructure:"current_proposer_agent,omitempty"`

	// ErredAgent corresponds to the JSON schema field "erred_agent".
	ErredAgent string `json:"erred_agent,omitempty,omitzero" yaml:"erred_agent,omitempty" mapstructure:"erred_agent,omitempty"`

	// ErredNegotiator corresponds to the JSON schema field "erred_negotiator".
	ErredNegotiator string `json:"erred_negotiator,omitempty,omitzero" yaml:"erred_negotiator,omitempty" mapstructure:"erred_negotiator,omitempty"`

	// ErrorDetails corresponds to the JSON schema field "error_details".
	ErrorDetails string `json:"error_details,omitempty,omitzero" yaml:"error_details,omitempty" mapstructure:"error_details,omitempty"`

	// HasError corresponds to the JSON schema field "has_error".
	HasError bool `json:"has_error,omitempty,omitzero" yaml:"has_error,omitempty" mapstructure:"has_error,omitempty"`

	// LastNegotiator corresponds to the JSON schema field "last_negotiator".
	LastNegotiator interface{} `json:"last_negotiator,omitempty,omitzero" yaml:"last_negotiator,omitempty" mapstructure:"last_negotiator,omitempty"`

	// LastThread corresponds to the JSON schema field "last_thread".
	LastThread string `json:"last_thread,omitempty,omitzero" yaml:"last_thread,omitempty" mapstructure:"last_thread,omitempty"`

	// LeftNegotiators corresponds to the JSON schema field "left_negotiators".
	LeftNegotiators []string `json:"left_negotiators,omitempty,omitzero" yaml:"left_negotiators,omitempty" mapstructure:"left_negotiators,omitempty"`

	// NAcceptances corresponds to the JSON schema field "n_acceptances".
	NAcceptances int `json:"n_acceptances,omitempty,omitzero" yaml:"n_acceptances,omitempty" mapstructure:"n_acceptances,omitempty"`

	// NNegotiators corresponds to the JSON schema field "n_negotiators".
	NNegotiators int `json:"n_negotiators,omitempty,omitzero" yaml:"n_negotiators,omitempty" mapstructure:"n_negotiators,omitempty"`

	// NewData corresponds to the JSON schema field "new_data".
	NewData [][]interface{} `json:"new_data,omitempty,omitzero" yaml:"new_data,omitempty" mapstructure:"new_data,omitempty"`

	// NewOffererAgents corresponds to the JSON schema field "new_offerer_agents".
	NewOffererAgents []interface{} `json:"new_offerer_agents,omitempty,omitzero" yaml:"new_offerer_agents,omitempty" mapstructure:"new_offerer_agents,omitempty"`

	// NewOffers corresponds to the JSON schema field "new_offers".
	NewOffers [][]interface{} `json:"new_offers,omitempty,omitzero" yaml:"new_offers,omitempty" mapstructure:"new_offers,omitempty"`

	// RelativeTime corresponds to the JSON schema field "relative_time".
	RelativeTime float64 `json:"relative_time,omitempty,omitzero" yaml:"relative_time,omitempty" mapstructure:"relative_time,omitempty"`

	// Results corresponds to the JSON schema field "results".
	Results interface{} `json:"results,omitempty,omitzero" yaml:"results,omitempty" mapstructure:"results,omitempty"`

	// Running corresponds to the JSON schema field "running".
	Running bool `json:"running,omitempty,omitzero" yaml:"running,omitempty" mapstructure:"running,omitempty"`

	// Started corresponds to the JSON schema field "started".
	Started bool `json:"started,omitempty,omitzero" yaml:"started,omitempty" mapstructure:"started,omitempty"`

	// Step corresponds to the JSON schema field "step".
	Step int `json:"step,omitempty,omitzero" yaml:"step,omitempty" mapstructure:"step,omitempty"`

	// Threads corresponds to the JSON schema field "threads".
	Threads SAOStateThreads `json:"threads,omitempty,omitzero" yaml:"threads,omitempty" mapstructure:"threads,omitempty"`

	// Time corresponds to the JSON schema field "time".
	Time float64 `json:"time,omitempty,omitzero" yaml:"time,omitempty" mapstructure:"time,omitempty"`

	// Timedout corresponds to the JSON schema field "timedout".
	Timedout bool `json:"timedout,omitempty,omitzero" yaml:"timedout,omitempty" mapstructure:"timedout,omitempty"`

	// Waiting corresponds to the JSON schema field "waiting".
	Waiting bool `json:"waiting,omitempty,omitzero" yaml:"waiting,omitempty" mapstructure:"waiting,omitempty"`
}

type SAOStateAgreement map[string]interface{}

type SAOStateAgreement_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOStateAgreement_0) UnmarshalJSON(value []byte) error {
	type Plain SAOStateAgreement_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SAOStateAgreement_0(plain)
	return nil
}

type SAOStateAgreement_1 []interface{}

type SAOStateCurrentData map[string]interface{}

type SAOStateCurrentData_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOStateCurrentData_0) UnmarshalJSON(value []byte) error {
	type Plain SAOStateCurrentData_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SAOStateCurrentData_0(plain)
	return nil
}

type SAOStateCurrentOffer map[string]interface{}

type SAOStateCurrentOffer_0 map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOStateCurrentOffer_0) UnmarshalJSON(value []byte) error {
	type Plain SAOStateCurrentOffer_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SAOStateCurrentOffer_0(plain)
	return nil
}

type SAOStateCurrentOffer_1 []interface{}

type SAOStateCurrentProposerAgent_0 *string

type SAOStateCurrentProposer_0 *string

type SAOStateLastNegotiator_0 *string

type SAOStateNewOffererAgentsElem_0 *string

type SAOStateThreads map[string]ThreadState

// UnmarshalJSON implements json.Unmarshaler.
func (j *SAOState) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain SAOState
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["broken"]; !ok || v == nil {
		plain.Broken = false
	}
	if v, ok := raw["erred_agent"]; !ok || v == nil {
		plain.ErredAgent = ""
	}
	if v, ok := raw["erred_negotiator"]; !ok || v == nil {
		plain.ErredNegotiator = ""
	}
	if v, ok := raw["error_details"]; !ok || v == nil {
		plain.ErrorDetails = ""
	}
	if v, ok := raw["has_error"]; !ok || v == nil {
		plain.HasError = false
	}
	if v, ok := raw["last_thread"]; !ok || v == nil {
		plain.LastThread = ""
	}
	if v, ok := raw["n_acceptances"]; !ok || v == nil {
		plain.NAcceptances = 0
	}
	if v, ok := raw["n_negotiators"]; !ok || v == nil {
		plain.NNegotiators = 0
	}
	if v, ok := raw["relative_time"]; !ok || v == nil {
		plain.RelativeTime = 0.0
	}
	if v, ok := raw["running"]; !ok || v == nil {
		plain.Running = false
	}
	if v, ok := raw["started"]; !ok || v == nil {
		plain.Started = false
	}
	if v, ok := raw["step"]; !ok || v == nil {
		plain.Step = 0
	}
	if v, ok := raw["time"]; !ok || v == nil {
		plain.Time = 0.0
	}
	if v, ok := raw["timedout"]; !ok || v == nil {
		plain.Timedout = false
	}
	if v, ok := raw["waiting"]; !ok || v == nil {
		plain.Waiting = false
	}
	*j = SAOState(plain)
	return nil
}

// Describes the semantic/ontological framework needed to correctly interpret the
// payload.
// The CFN routing layer uses this to select appropriate cognitive engines (CEs).
type Semantic struct {
	// OntologyRef corresponds to the JSON schema field "ontology_ref".
	OntologyRef string `json:"ontology_ref" yaml:"ontology_ref" mapstructure:"ontology_ref"`

	// Provenance corresponds to the JSON schema field "provenance".
	Provenance *SemanticProvenance `json:"provenance,omitempty,omitzero" yaml:"provenance,omitempty" mapstructure:"provenance,omitempty"`

	// SchemaID corresponds to the JSON schema field "schema_id".
	SchemaID string `json:"schema_id" yaml:"schema_id" mapstructure:"schema_id"`
}

// Schema and encoding metadata for the payload.
type SemanticContext struct {
	// Encoding corresponds to the JSON schema field "encoding".
	Encoding SemanticContextEncoding `json:"encoding,omitempty,omitzero" yaml:"encoding,omitempty" mapstructure:"encoding,omitempty"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion string `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`
}

type SemanticContextEncoding string

const SemanticContextEncodingHybrid SemanticContextEncoding = "hybrid"
const SemanticContextEncodingJson SemanticContextEncoding = "json"
const SemanticContextEncodingStructuredText SemanticContextEncoding = "structured_text"

var enumValues_SemanticContextEncoding = []interface{}{
	"json",
	"structured_text",
	"hybrid",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SemanticContextEncoding) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SemanticContextEncoding {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SemanticContextEncoding, v)
	}
	*j = SemanticContextEncoding(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SemanticContext) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in SemanticContext: required")
	}
	type Plain SemanticContext
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["encoding"]; !ok || v == nil {
		plain.Encoding = "json"
	}
	*j = SemanticContext(plain)
	return nil
}

// Tracks the origin and lineage of a message - who created it, from what source,
// and through which transformations. Fields TBD.
type SemanticProvenance map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Semantic) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ontology_ref"]; raw != nil && !ok {
		return fmt.Errorf("field ontology_ref in Semantic: required")
	}
	if _, ok := raw["schema_id"]; raw != nil && !ok {
		return fmt.Errorf("field schema_id in Semantic: required")
	}
	type Plain Semantic
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Semantic(plain)
	return nil
}

// Per-thread state in a GB (Generalized Bargaining) negotiation round.
//
// NegMAS source: negmas.gb.common.ThreadState
type ThreadState struct {
	// AcceptedOffers corresponds to the JSON schema field "accepted_offers".
	AcceptedOffers []*ThreadStateAcceptedOffersElem `json:"accepted_offers,omitempty,omitzero" yaml:"accepted_offers,omitempty" mapstructure:"accepted_offers,omitempty"`

	// NewData corresponds to the JSON schema field "new_data".
	NewData *ThreadStateNewData `json:"new_data,omitempty,omitzero" yaml:"new_data,omitempty" mapstructure:"new_data,omitempty"`

	// NewOffer corresponds to the JSON schema field "new_offer".
	NewOffer *ThreadStateNewOffer `json:"new_offer,omitempty,omitzero" yaml:"new_offer,omitempty" mapstructure:"new_offer,omitempty"`

	// NewResponses corresponds to the JSON schema field "new_responses".
	NewResponses ThreadStateNewResponses `json:"new_responses,omitempty,omitzero" yaml:"new_responses,omitempty" mapstructure:"new_responses,omitempty"`
}

type ThreadStateAcceptedOffersElem map[string]interface{}

type ThreadStateAcceptedOffersElem_0 map[string]interface{}

type NegotiateSemanticContextSaoState_0 = SAOState

// UnmarshalJSON implements json.Unmarshaler.
func (j *ThreadStateNewData_0) UnmarshalJSON(value []byte) error {
	type Plain ThreadStateNewData_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ThreadStateNewData_0(plain)
	return nil
}

type ThreadStateNewData_0 map[string]interface{}

type ThreadStateNewOffer_0 map[string]interface{}

type ThreadStateAcceptedOffersElem_1 []interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ThreadStateAcceptedOffersElem_0) UnmarshalJSON(value []byte) error {
	type Plain ThreadStateAcceptedOffersElem_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ThreadStateAcceptedOffersElem_0(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ThreadStateNewOffer_0) UnmarshalJSON(value []byte) error {
	type Plain ThreadStateNewOffer_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ThreadStateNewOffer_0(plain)
	return nil
}

type ThreadStateNewOffer_1 []interface{}

type ThreadStateNewOffer map[string]interface{}

type ThreadStateNewResponses map[string]ResponseType

type SABHeaderPolicy_0 = PolicyLabel

type SABHeaderMessage_0 = Message

type ThreadStateNewData map[string]interface{}

type SABHeaderAttributes_0 = SABAttributes

type SABHeaderContextSemanticProvenance_0 = Provenance

type NegotiateSemanticContextSaoResponse_0 = SAOResponse

type NegotiateSemanticContextNmi_0 = SAONMI

type ContextSemanticProvenance_0 = Provenance

type SABL9PayloadData_0 = SABIntentPayloadData

type SABL9PayloadData_1 = SABNegotiatePayloadData

type SABL9PayloadData_2 = SABCommitPayloadData

type ContextSemantic_0 = Semantic

type SABHeaderContext_0 = Context

type SABHeaderContextEpistemic_0 = Epistemic

type SABHeaderContextSemantic_0 = Semantic

type SemanticProvenance_0 = Provenance

type ContextEpistemic_0 = Epistemic
