# generated by datamodel-codegen:
#   filename:  l9.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Actor(BaseModel):
    id: str = Field(..., title="Id")
    type: str = Field(..., title="Type")
    name: str = Field(..., title="Name")
    role: str = Field(..., title="Role")


class Epistemic(BaseModel):
    pass


class Group(BaseModel):
    id: str = Field(..., title="Id")
    name: str = Field(..., title="Name")


class L9Payload(BaseModel):
    type: str = Field(..., title="Type")
    data: dict[str, Any] = Field(..., title="Data")


class PolicyLabel(BaseModel):
    sensitivity: str = Field(..., title="Sensitivity")
    propagation: str = Field(..., title="Propagation")
    retention_policy: str = Field(..., title="Retention Policy")


class Provenance(BaseModel):
    pass


class SemanticContext(BaseModel):
    schema_id: str = Field(..., title="Schema Id")
    ontology_ref: str = Field(..., title="Ontology Ref")
    cognition_protocol: str = Field(..., title="Cognition Protocol")


class L9Header(BaseModel):
    protocol: str = Field(..., title="Protocol")
    version: str = Field(..., title="Version")
    kind: str = Field(..., title="Kind")
    sub_kind: str = Field(..., title="Sub Kind")
    group: Group
    actors: list[Actor] = Field(..., title="Actors")
    semantic: SemanticContext
    policy: PolicyLabel | None = None
    provenance: Provenance | None = None
    epistemic: Epistemic | None = None


class L9(BaseModel):
    header: L9Header
    payload: L9Payload
