# generated by datamodel-codegen:
#   filename:  tfp_schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class RoleAssignment(BaseModel):
    agent_id: str = Field(..., title='Agent Id')
    role: str = Field(..., title='Role')
    responsible_for: list[str] = Field([], title='Responsible For')


class SkillClaim(BaseModel):
    skill: str = Field(..., title='Skill')
    proficiency: float = Field(..., ge=0.0, le=1.0, title='Proficiency')


class SkillRequirement(BaseModel):
    skill: str = Field(..., title='Skill')
    min_proficiency: float = Field(0.0, ge=0.0, le=1.0, title='Min Proficiency')
    weight: float = Field(1.0, ge=0.0, title='Weight')
    mandatory: bool = Field(True, title='Mandatory')


class TFPOperation(str, Enum):
    POLL_OPEN = 'poll_open'
    BID = 'bid'
    DECLINE = 'decline'
    CLARIFY = 'clarify'
    SELECT = 'select'
    ACCEPT = 'accept'
    REJECT = 'reject'
    FORM_FAILED = 'form_failed'
    FORM_CONVERGED = 'form_converged'
    RE_POLL = 're_poll'


class TaskSpec(BaseModel):
    task_id: str = Field(..., title='Task Id')
    description: str = Field(..., title='Description')
    objective: str | None = Field(None, title='Objective')
    deadline: str | None = Field(None, title='Deadline')


class TeamSelection(BaseModel):
    members: list[str] = Field([], title='Members')
    roles: list[RoleAssignment] = Field(default_factory=list, title='Roles')
    coverage: float = Field(0.0, ge=0.0, le=1.0, title='Coverage')
    unmet_skills: list[str] = Field([], title='Unmet Skills')
    aggregate_fit: float | None = Field(None, ge=0.0, le=1.0, title='Aggregate Fit')


class TFPSubkind(str, Enum):
    TEAM_FORM = 'team_form'
    TEAM_FORM_CONVERGED = 'team_form_converged'
    TEAM_FORM_FAILURE = 'team_form_failure'


class CandidateOffer(BaseModel):
    skills: list[SkillClaim] = Field(default_factory=list, title='Skills')
    availability: float | None = Field(None, ge=0.0, le=1.0, title='Availability')
    fit_score: float | None = Field(None, ge=0.0, le=1.0, title='Fit Score')
    cost: float | None = Field(None, title='Cost')
    notes: str | None = Field(None, title='Notes')


class TFPPayload(BaseModel):
    operation: TFPOperation
    poll_id: str = Field(..., title='Poll Id')
    task: TaskSpec | None = None
    required_skills: list[SkillRequirement] = Field(
        default_factory=list, title='Required Skills'
    )
    offer: CandidateOffer | None = None
    selection: TeamSelection | None = None
    reason: str | None = Field(None, title='Reason')
    reasoning_summary: str | None = Field(None, title='Reasoning Summary')
