name: ioc-cfn-protocols-models CI workflow

on:
  # we want pull requests so we can build(test) but not push to image registry
  push:
    branches:
      - 'main'

    # only build when important files change
    #paths:
    #  - 'app/**'
    #  - '.github/workflows/ci.yaml'
    #tags:
    #  - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

# Grant read access for GITHUB_TOKEN on all jobs
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  ################################## Code Checkout ##############################
  ###############################################################################
  checkout-unit-tests:
    name: checkout & unit test
    runs-on:
      group: arc-runner-set

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # The branch, tag or SHA to checkout, otherwise, uses the default branch.
          ref: ${{ github.ref }}
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: ''
          # Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching
          # Default: true
          clean: true
          # Whether to download Git-LFS files
          # Default: false
          lfs: ''
          # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
          # recursively checkout submodules.
          # Default: false
          submodules: ''

  ################################## Unit Test ##################################
  ###############################################################################

      - name: Unit Tests
        run: |
          ls -l /usr/local/bin
          #chmod +x scripts/unit-test.sh
          bash scripts/unit-test.sh

  ################################## Send Status for PR Checks ###########################
  ########################################################################################
  reusable-workflow-ci-status:
    name: Reusable Workflow CI Status
    needs: [ checkout-unit-tests ]
    if: always()
    runs-on:
      group: arc-runner-set
    steps:
      - name: report failure
        if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
        run: |
          echo -e "\033[31m*** WORKFLOW FAILED ***\033[0m"
          exit 1
      - name: report success
        run: |
          echo -e "\033[1;36m*** WORKFLOW SUCCESS ***\033[0m"
          exit 0
